import type { VenueWithCity, VenueWithCocktails, City, Cocktail } from "./types";

const cities: City[] = [
  { id: "1", name: "Mumbai", slug: "mumbai", state: "Maharashtra", country: "India", lat: 19.0760, lng: 72.8777 },
  { id: "2", name: "Delhi", slug: "delhi", state: "Delhi", country: "India", lat: 28.6139, lng: 77.2090 },
  { id: "3", name: "Bangalore", slug: "bangalore", state: "Karnataka", country: "India", lat: 12.9716, lng: 77.5946 },
  { id: "4", name: "Goa", slug: "goa", state: "Goa", country: "India", lat: 15.2993, lng: 74.1240 },
  { id: "5", name: "Hyderabad", slug: "hyderabad", state: "Telangana", country: "India", lat: 17.3850, lng: 78.4867 },
  { id: "6", name: "Pune", slug: "pune", state: "Maharashtra", country: "India", lat: 18.5204, lng: 73.8567 },
];

const cocktails: (Cocktail & { venue_slug: string })[] = [
  // ===== SIDECAR DELHI (12 drinks) =====
  { id: "c1", venue_id: "v7", venue_slug: "sidecar-delhi", name: "Sidecar of India", slug: "sidecar-of-india", description: "Ghee-washed gin, vetiver cordial, tamarind, lime. The bar namesake — savory, cooling, unmistakably Indian.", price_inr: 950, base_spirit: "gin", flavor_tags: ["savory","herbal","citrus"], ingredients: [], image_url: null, is_signature: true },
  { id: "c2", venue_id: "v7", venue_slug: "sidecar-delhi", name: "Mumbai Mule", slug: "mumbai-mule", description: "Cashew feni, house-made ginger beer, lime, curry leaf garnish.", price_inr: 850, base_spirit: "feni", flavor_tags: ["spicy","tropical","refreshing"], ingredients: [], image_url: null, is_signature: true },
  { id: "c3", venue_id: "v7", venue_slug: "sidecar-delhi", name: "Dilli 6", slug: "dilli-6", description: "Mezcal, jamun cordial, chaat masala tincture, salted rim. Old Delhi summer in a glass.", price_inr: 1050, base_spirit: "mezcal", flavor_tags: ["smoky","tart","savory"], ingredients: [], image_url: null, is_signature: true },
  { id: "c1a", venue_id: "v7", venue_slug: "sidecar-delhi", name: "Punjab Gimlet", slug: "punjab-gimlet", description: "Sarson-infused gin, lime cordial, fenugreek bitters. Like dhaba meets cocktail bar.", price_inr: 900, base_spirit: "gin", flavor_tags: ["herbal","tart","savory"], ingredients: [], image_url: null, is_signature: false },
  { id: "c1b", venue_id: "v7", venue_slug: "sidecar-delhi", name: "Chettinad Daiquiri", slug: "chettinad-daiquiri", description: "Aged rum, black pepper syrup, kari leaves, lime. South Indian heat in a coupe.", price_inr: 950, base_spirit: "rum", flavor_tags: ["spicy","tropical","tart"], ingredients: [], image_url: null, is_signature: false },
  { id: "c1c", venue_id: "v7", venue_slug: "sidecar-delhi", name: "Konkan Sour", slug: "konkan-sour", description: "Coconut feni, kokum reduction, aquafaba, sea salt.", price_inr: 850, base_spirit: "feni", flavor_tags: ["tropical","tart","silky"], ingredients: [], image_url: null, is_signature: false },
  { id: "c1d", venue_id: "v7", venue_slug: "sidecar-delhi", name: "Bengal Tiger", slug: "bengal-tiger", description: "Whisky, gondhoraj lime cordial, mustard oil rinse. Calcutta on a coaster.", price_inr: 1000, base_spirit: "whisky", flavor_tags: ["citrus","savory","aromatic"], ingredients: [], image_url: null, is_signature: false },
  { id: "c1e", venue_id: "v7", venue_slug: "sidecar-delhi", name: "Goa Highball", slug: "goa-highball", description: "Cashew feni, soda, fresh kokum, mint. Beach in a tall glass.", price_inr: 750, base_spirit: "feni", flavor_tags: ["tropical","refreshing","tart"], ingredients: [], image_url: null, is_signature: false },
  { id: "c1f", venue_id: "v7", venue_slug: "sidecar-delhi", name: "Kashmir Express", slug: "kashmir-express", description: "Kahwa-infused gin, saffron syrup, rose, lemon.", price_inr: 950, base_spirit: "gin", flavor_tags: ["floral","aromatic","warming"], ingredients: [], image_url: null, is_signature: false },
  { id: "c1g", venue_id: "v7", venue_slug: "sidecar-delhi", name: "Old Monk, New Tricks", slug: "old-monk-new-tricks", description: "Old Monk reduction, vanilla, cacao bitters, smoked ice.", price_inr: 900, base_spirit: "rum", flavor_tags: ["smoky","sweet","rich"], ingredients: [], image_url: null, is_signature: false },
  { id: "c1h", venue_id: "v7", venue_slug: "sidecar-delhi", name: "Rajasthani Mary", slug: "rajasthani-mary", description: "Vodka, tomato, raw mango, mathania chili, kala namak. Bloody Mary, reimagined.", price_inr: 800, base_spirit: "vodka", flavor_tags: ["spicy","savory","tart"], ingredients: [], image_url: null, is_signature: false },
  { id: "c1i", venue_id: "v7", venue_slug: "sidecar-delhi", name: "Hill Station", slug: "hill-station", description: "Single malt, honey, ginger, lemon. Built for Himalayan winters.", price_inr: 1200, base_spirit: "whisky", flavor_tags: ["warming","sweet","citrus"], ingredients: [], image_url: null, is_signature: false },

  // ===== HOME DELHI (11 drinks) =====
  { id: "c4", venue_id: "v8", venue_slug: "home-delhi", name: "Mahua Sour", slug: "mahua-sour", description: "Mahua spirit from Chhattisgarh, jaggery syrup, lime, aquafaba. Floral, grassy, unlike anything else.", price_inr: 900, base_spirit: "mahua", flavor_tags: ["floral","tart","silky"], ingredients: [], image_url: null, is_signature: true },
  { id: "c5", venue_id: "v8", venue_slug: "home-delhi", name: "Spice Bazaar", slug: "spice-bazaar", description: "Dark rum, garam masala syrup, orange peel, cardamom bitters. Dessert in a coupe.", price_inr: 850, base_spirit: "rum", flavor_tags: ["spiced","warming","sweet"], ingredients: [], image_url: null, is_signature: true },
  { id: "c4a", venue_id: "v8", venue_slug: "home-delhi", name: "Tadka", slug: "tadka", description: "Gin, curry leaf oil, asafoetida tincture, lime. The kitchen tempering, in a glass.", price_inr: 950, base_spirit: "gin", flavor_tags: ["herbal","savory","citrus"], ingredients: [], image_url: null, is_signature: false },
  { id: "c4b", venue_id: "v8", venue_slug: "home-delhi", name: "Achaar Martini", slug: "achaar-martini", description: "Vodka, mango pickle brine, cardamom. Briny, spicy, oddly addictive.", price_inr: 850, base_spirit: "vodka", flavor_tags: ["savory","spicy","umami"], ingredients: [], image_url: null, is_signature: false },
  { id: "c4c", venue_id: "v8", venue_slug: "home-delhi", name: "Imli Old Fashioned", slug: "imli-old-fashioned", description: "Bourbon, tamarind syrup, jaggery, smoked salt.", price_inr: 1000, base_spirit: "bourbon", flavor_tags: ["smoky","tart","sweet"], ingredients: [], image_url: null, is_signature: false },
  { id: "c4d", venue_id: "v8", venue_slug: "home-delhi", name: "Ghee-Washed Negroni", slug: "ghee-negroni", description: "Brown butter ghee-washed gin, sweet vermouth, Campari. Velvet on velvet.", price_inr: 1100, base_spirit: "gin", flavor_tags: ["bitter","rich","silky"], ingredients: [], image_url: null, is_signature: false },
  { id: "c4e", venue_id: "v8", venue_slug: "home-delhi", name: "Dadi's Garden", slug: "dadis-garden", description: "Tulsi-infused gin, honey, lime, fresh basil. Grandmother's herb patch.", price_inr: 800, base_spirit: "gin", flavor_tags: ["herbal","floral","sweet"], ingredients: [], image_url: null, is_signature: false },
  { id: "c4f", venue_id: "v8", venue_slug: "home-delhi", name: "Filter Coffee Espresso Martini", slug: "filter-coffee-em", description: "Vodka, South Indian filter coffee, jaggery, cardamom.", price_inr: 950, base_spirit: "vodka", flavor_tags: ["bitter","sweet","aromatic"], ingredients: [], image_url: null, is_signature: false },
  { id: "c4g", venue_id: "v8", venue_slug: "home-delhi", name: "Saunf Highball", slug: "saunf-highball", description: "Whisky, fennel cordial, lemon, soda. The post-meal mukhwas, fermented.", price_inr: 850, base_spirit: "whisky", flavor_tags: ["herbal","refreshing","sweet"], ingredients: [], image_url: null, is_signature: false },
  { id: "c4h", venue_id: "v8", venue_slug: "home-delhi", name: "Coconut Toddy Sour", slug: "coconut-toddy-sour", description: "Fresh palm toddy, honey, lime, egg white. Funky, delicate, alive.", price_inr: 800, base_spirit: "toddy", flavor_tags: ["funky","silky","tart"], ingredients: [], image_url: null, is_signature: false },
  { id: "c4i", venue_id: "v8", venue_slug: "home-delhi", name: "Paan Daiquiri", slug: "paan-daiquiri", description: "Aged rum, betel leaf, gulkand, lime. Dessert reset for your palate.", price_inr: 900, base_spirit: "rum", flavor_tags: ["floral","sweet","aromatic"], ingredients: [], image_url: null, is_signature: false },

  // ===== BOMBAY CANTEEN (10 drinks) =====
  { id: "c6", venue_id: "v1", venue_slug: "the-bombay-canteen-mumbai", name: "Gulkand Gimlet", slug: "gulkand-gimlet", description: "Gin, rose petal jam, fresh lime. A Calcutta summer translated.", price_inr: 750, base_spirit: "gin", flavor_tags: ["floral","rose","citrus"], ingredients: [], image_url: null, is_signature: true },
  { id: "c7", venue_id: "v1", venue_slug: "the-bombay-canteen-mumbai", name: "Kokum Negroni", slug: "kokum-negroni", description: "Gin, sweet vermouth, kokum reduction instead of Campari. Tropical Italian.", price_inr: 800, base_spirit: "gin", flavor_tags: ["tart","bitter","fruity"], ingredients: [], image_url: null, is_signature: true },
  { id: "c6a", venue_id: "v1", venue_slug: "the-bombay-canteen-mumbai", name: "TBC Sour", slug: "tbc-sour", description: "Whisky, jaggery syrup, kala khatta, aquafaba. Bombay roadside chuski, grown up.", price_inr: 800, base_spirit: "whisky", flavor_tags: ["tart","sweet","silky"], ingredients: [], image_url: null, is_signature: false },
  { id: "c6b", venue_id: "v1", venue_slug: "the-bombay-canteen-mumbai", name: "Cutting Espresso", slug: "cutting-espresso", description: "Vodka, cold brew, jaggery, cardamom foam. Mumbai chai, caffeinated.", price_inr: 750, base_spirit: "vodka", flavor_tags: ["bitter","sweet","aromatic"], ingredients: [], image_url: null, is_signature: false },
  { id: "c6c", venue_id: "v1", venue_slug: "the-bombay-canteen-mumbai", name: "Banganapalle Daiquiri", slug: "banganapalle-daiquiri", description: "White rum, banganapalle mango, lime, mint.", price_inr: 800, base_spirit: "rum", flavor_tags: ["tropical","sweet","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "c6d", venue_id: "v1", venue_slug: "the-bombay-canteen-mumbai", name: "Curry Leaf Margarita", slug: "curry-leaf-margarita", description: "Tequila, curry leaf-infused triple sec, lime, sea salt.", price_inr: 850, base_spirit: "tequila", flavor_tags: ["herbal","tart","savory"], ingredients: [], image_url: null, is_signature: false },
  { id: "c6e", venue_id: "v1", venue_slug: "the-bombay-canteen-mumbai", name: "Solkadhi Spritz", slug: "solkadhi-spritz", description: "Aperol, kokum, coconut water, prosecco. Konkan aperitivo.", price_inr: 800, base_spirit: "aperol", flavor_tags: ["tart","refreshing","tropical"], ingredients: [], image_url: null, is_signature: false },
  { id: "c6f", venue_id: "v1", venue_slug: "the-bombay-canteen-mumbai", name: "Aam Panna Collins", slug: "aam-panna-collins", description: "Gin, raw mango, mint, black salt, soda. Summer in Goregaon.", price_inr: 750, base_spirit: "gin", flavor_tags: ["tart","savory","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "c6g", venue_id: "v1", venue_slug: "the-bombay-canteen-mumbai", name: "Bombay Duck", slug: "bombay-duck", description: "Mezcal, kokum, lime, smoked salt. Smoky and saline.", price_inr: 950, base_spirit: "mezcal", flavor_tags: ["smoky","tart","savory"], ingredients: [], image_url: null, is_signature: false },
  { id: "c6h", venue_id: "v1", venue_slug: "the-bombay-canteen-mumbai", name: "Falooda Fizz", slug: "falooda-fizz", description: "Gin, rose syrup, vermicelli, basil seeds, soda. Yes, really.", price_inr: 800, base_spirit: "gin", flavor_tags: ["floral","sweet","refreshing"], ingredients: [], image_url: null, is_signature: false },

  // ===== SORO GOA (10 drinks) =====
  { id: "c8", venue_id: "v18", venue_slug: "soro-goa", name: "Feni Old Fashioned", slug: "feni-old-fashioned", description: "Cashew feni aged in oak, demerara, angostura, orange peel.", price_inr: 650, base_spirit: "feni", flavor_tags: ["oaky","bitter","tropical"], ingredients: [], image_url: null, is_signature: true },
  { id: "c9", venue_id: "v18", venue_slug: "soro-goa", name: "Sol Kadhi Margarita", slug: "sol-kadhi-margarita", description: "Tequila, kokum, coconut milk, lime, chili salt. Liquid sol kadhi with a kick.", price_inr: 700, base_spirit: "tequila", flavor_tags: ["coconut","tart","spicy"], ingredients: [], image_url: null, is_signature: true },
  { id: "c8a", venue_id: "v18", venue_slug: "soro-goa", name: "Assagao Garden", slug: "assagao-garden", description: "Gin, basil, lemongrass, soda. Whatever's growing, in a glass.", price_inr: 600, base_spirit: "gin", flavor_tags: ["herbal","refreshing","floral"], ingredients: [], image_url: null, is_signature: false },
  { id: "c8b", venue_id: "v18", venue_slug: "soro-goa", name: "Recheado Mary", slug: "recheado-mary", description: "Vodka, tomato, recheado masala, lime. Goan Bloody Mary.", price_inr: 650, base_spirit: "vodka", flavor_tags: ["spicy","savory","tart"], ingredients: [], image_url: null, is_signature: false },
  { id: "c8c", venue_id: "v18", venue_slug: "soro-goa", name: "Cashew Caipirinha", slug: "cashew-caipirinha", description: "Cashew feni, jaggery, lime, muddled.", price_inr: 600, base_spirit: "feni", flavor_tags: ["tropical","tart","sweet"], ingredients: [], image_url: null, is_signature: false },
  { id: "c8d", venue_id: "v18", venue_slug: "soro-goa", name: "Mandovi Spritz", slug: "mandovi-spritz", description: "Aperol, prosecco, kokum, soda. Sunset on the river.", price_inr: 750, base_spirit: "aperol", flavor_tags: ["bitter","tart","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "c8e", venue_id: "v18", venue_slug: "soro-goa", name: "Ponda Punch", slug: "ponda-punch", description: "Dark rum, pineapple, lime, jaggery, nutmeg.", price_inr: 700, base_spirit: "rum", flavor_tags: ["tropical","sweet","spiced"], ingredients: [], image_url: null, is_signature: false },
  { id: "c8f", venue_id: "v18", venue_slug: "soro-goa", name: "Coconut Negroni", slug: "coconut-negroni", description: "Coconut-fat-washed gin, sweet vermouth, Campari.", price_inr: 800, base_spirit: "gin", flavor_tags: ["bitter","tropical","silky"], ingredients: [], image_url: null, is_signature: false },
  { id: "c8g", venue_id: "v18", venue_slug: "soro-goa", name: "Susegad Sour", slug: "susegad-sour", description: "Whisky, urak, lime, honey. The Goan state of mind.", price_inr: 750, base_spirit: "whisky", flavor_tags: ["tart","tropical","sweet"], ingredients: [], image_url: null, is_signature: false },
  { id: "c8h", venue_id: "v18", venue_slug: "soro-goa", name: "Pao With Wine", slug: "pao-with-wine", description: "Red wine, cinnamon, clove, orange. Goan mulled wine for cool nights.", price_inr: 650, base_spirit: "wine", flavor_tags: ["spiced","warming","fruity"], ingredients: [], image_url: null, is_signature: false },

  // ===== PCO DELHI (10 drinks) =====
  { id: "c10", venue_id: "v10", venue_slug: "pco-delhi", name: "Pink Flamingo", slug: "pink-flamingo", description: "Vodka, fresh beetroot, rose syrup, lime, egg white. Tart, floral, Jaipur sunset.", price_inr: 850, base_spirit: "vodka", flavor_tags: ["floral","tart","earthy"], ingredients: [], image_url: null, is_signature: true },
  { id: "c11", venue_id: "v10", venue_slug: "pco-delhi", name: "Tobacco Fashioned", slug: "tobacco-fashioned", description: "Tobacco-infused bourbon, demerara, bitters. No gimmick.", price_inr: 1100, base_spirit: "bourbon", flavor_tags: ["smoky","rich","boozy"], ingredients: [], image_url: null, is_signature: true },
  { id: "c10a", venue_id: "v10", venue_slug: "pco-delhi", name: "Smoking Gun", slug: "smoking-gun", description: "Mezcal, lapsang souchong, agave, lime. Smoke layered on smoke.", price_inr: 1000, base_spirit: "mezcal", flavor_tags: ["smoky","earthy","tart"], ingredients: [], image_url: null, is_signature: false },
  { id: "c10b", venue_id: "v10", venue_slug: "pco-delhi", name: "Velvet Rope", slug: "velvet-rope", description: "Cognac, port wine reduction, dark chocolate bitters. Decadent.", price_inr: 1200, base_spirit: "cognac", flavor_tags: ["rich","sweet","boozy"], ingredients: [], image_url: null, is_signature: false },
  { id: "c10c", venue_id: "v10", venue_slug: "pco-delhi", name: "Speak Easy", slug: "speak-easy", description: "Rye whisky, sweet vermouth, absinthe rinse, orange. Pre-prohibition perfection.", price_inr: 1050, base_spirit: "rye", flavor_tags: ["herbal","boozy","aromatic"], ingredients: [], image_url: null, is_signature: false },
  { id: "c10d", venue_id: "v10", venue_slug: "pco-delhi", name: "Vasant Vihar Spritz", slug: "vasant-vihar-spritz", description: "Gin, elderflower, prosecco, lime. Light, floral, dangerous.", price_inr: 900, base_spirit: "gin", flavor_tags: ["floral","refreshing","tart"], ingredients: [], image_url: null, is_signature: false },
  { id: "c10e", venue_id: "v10", venue_slug: "pco-delhi", name: "Black Jack", slug: "black-jack", description: "Activated charcoal vodka, blackberry, lime, soda.", price_inr: 850, base_spirit: "vodka", flavor_tags: ["earthy","tart","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "c10f", venue_id: "v10", venue_slug: "pco-delhi", name: "Code Red", slug: "code-red", description: "Tequila, beetroot, chili, lime, agave. The fight or flight cocktail.", price_inr: 950, base_spirit: "tequila", flavor_tags: ["spicy","earthy","tart"], ingredients: [], image_url: null, is_signature: false },
  { id: "c10g", venue_id: "v10", venue_slug: "pco-delhi", name: "Gold Rush", slug: "gold-rush", description: "Bourbon, honey, lemon. Three ingredients, perfectly executed.", price_inr: 950, base_spirit: "bourbon", flavor_tags: ["sweet","tart","warming"], ingredients: [], image_url: null, is_signature: false },
  { id: "c10h", venue_id: "v10", venue_slug: "pco-delhi", name: "Whisper", slug: "whisper", description: "Sake, gin, cucumber, elderflower, lime.", price_inr: 1000, base_spirit: "gin", flavor_tags: ["floral","refreshing","crisp"], ingredients: [], image_url: null, is_signature: false },

  // ===== TEDDY BOY DELHI (10 drinks) =====
  { id: "c12", venue_id: "v12", venue_slug: "teddy-boy-delhi", name: "Chai Old Fashioned", slug: "chai-old-fashioned", description: "Chai-infused rye, jaggery syrup, black cardamom bitters. Indian breakfast at midnight.", price_inr: 850, base_spirit: "rye", flavor_tags: ["spiced","warming","aromatic"], ingredients: [], image_url: null, is_signature: true },
  { id: "c12a", venue_id: "v12", venue_slug: "teddy-boy-delhi", name: "Mezcal Mela", slug: "mezcal-mela", description: "Mezcal, hibiscus, lime, chili tincture.", price_inr: 950, base_spirit: "mezcal", flavor_tags: ["smoky","floral","spicy"], ingredients: [], image_url: null, is_signature: false },
  { id: "c12b", venue_id: "v12", venue_slug: "teddy-boy-delhi", name: "Lodi Garden", slug: "lodi-garden", description: "Gin, basil, cucumber, mint, lime. Like the park itself.", price_inr: 800, base_spirit: "gin", flavor_tags: ["herbal","refreshing","crisp"], ingredients: [], image_url: null, is_signature: false },
  { id: "c12c", venue_id: "v12", venue_slug: "teddy-boy-delhi", name: "Rooh Afza Daiquiri", slug: "rooh-afza-daiquiri", description: "White rum, rooh afza, lime, mint. Diaspora summer in liquid form.", price_inr: 750, base_spirit: "rum", flavor_tags: ["floral","sweet","tart"], ingredients: [], image_url: null, is_signature: false },
  { id: "c12d", venue_id: "v12", venue_slug: "teddy-boy-delhi", name: "Mocha Negroni", slug: "mocha-negroni", description: "Coffee-infused gin, sweet vermouth, Campari, cacao bitters.", price_inr: 950, base_spirit: "gin", flavor_tags: ["bitter","rich","aromatic"], ingredients: [], image_url: null, is_signature: false },
  { id: "c12e", venue_id: "v12", venue_slug: "teddy-boy-delhi", name: "Khari Sour", slug: "khari-sour", description: "Whisky, salted lassi, lime, jaggery. Yes, salted yogurt cocktail. Trust.", price_inr: 850, base_spirit: "whisky", flavor_tags: ["savory","tart","silky"], ingredients: [], image_url: null, is_signature: false },
  { id: "c12f", venue_id: "v12", venue_slug: "teddy-boy-delhi", name: "Daru Sutta", slug: "daru-sutta", description: "Smoked whisky, tobacco bitters, demerara. The drink your uncle would order.", price_inr: 1100, base_spirit: "whisky", flavor_tags: ["smoky","boozy","rich"], ingredients: [], image_url: null, is_signature: false },
  { id: "c12g", venue_id: "v12", venue_slug: "teddy-boy-delhi", name: "Red Velvet Negroni", slug: "red-velvet-negroni", description: "Gin, sweet vermouth, Campari, beetroot reduction.", price_inr: 900, base_spirit: "gin", flavor_tags: ["bitter","earthy","rich"], ingredients: [], image_url: null, is_signature: false },
  { id: "c12h", venue_id: "v12", venue_slug: "teddy-boy-delhi", name: "Tarapith Sour", slug: "tarapith-sour", description: "Bourbon, gondhoraj lime, honey, egg white. Bengali winter in a coupe.", price_inr: 950, base_spirit: "bourbon", flavor_tags: ["citrus","sweet","silky"], ingredients: [], image_url: null, is_signature: false },
  { id: "c12i", venue_id: "v12", venue_slug: "teddy-boy-delhi", name: "Last Train To Sultanpur", slug: "last-train-sultanpur", description: "Aged rum, jaggery, tamarind, smoke. Going home, slowly.", price_inr: 950, base_spirit: "rum", flavor_tags: ["smoky","sweet","tart"], ingredients: [], image_url: null, is_signature: false },

  // ===== FOR THE RECORD GOA (10 drinks) =====
  { id: "c13", venue_id: "v19", venue_slug: "for-the-record-goa", name: "Yuzu Highball", slug: "yuzu-highball", description: "Japanese whisky, yuzu juice, soda, large rock. Served while Kind of Blue plays.", price_inr: 900, base_spirit: "whisky", flavor_tags: ["citrus","crisp","refreshing"], ingredients: [], image_url: null, is_signature: true },
  { id: "c14", venue_id: "v19", venue_slug: "for-the-record-goa", name: "Toddy Sour", slug: "toddy-sour", description: "Fresh Goan palm toddy, whisky, lime, egg white. Local meets Japanese precision.", price_inr: 750, base_spirit: "toddy", flavor_tags: ["funky","tart","silky"], ingredients: [], image_url: null, is_signature: true },
  { id: "c13a", venue_id: "v19", venue_slug: "for-the-record-goa", name: "B-Side", slug: "b-side", description: "Gin, shiso, yuzu, soda.", price_inr: 850, base_spirit: "gin", flavor_tags: ["herbal","citrus","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "c13b", venue_id: "v19", venue_slug: "for-the-record-goa", name: "Vinyl Negroni", slug: "vinyl-negroni", description: "Gin, sweet vermouth, Campari, smoke. Slowest sipper in Goa.", price_inr: 950, base_spirit: "gin", flavor_tags: ["bitter","smoky","rich"], ingredients: [], image_url: null, is_signature: false },
  { id: "c13c", venue_id: "v19", venue_slug: "for-the-record-goa", name: "Side One Track One", slug: "side-one-track-one", description: "Whisky, plum sake, lime. Opening cut.", price_inr: 1000, base_spirit: "whisky", flavor_tags: ["tart","aromatic","crisp"], ingredients: [], image_url: null, is_signature: false },
  { id: "c13d", venue_id: "v19", venue_slug: "for-the-record-goa", name: "Coltrane", slug: "coltrane", description: "Mezcal, espresso, agave. Smoky and caffeinated.", price_inr: 1100, base_spirit: "mezcal", flavor_tags: ["smoky","bitter","rich"], ingredients: [], image_url: null, is_signature: false },
  { id: "c13e", venue_id: "v19", venue_slug: "for-the-record-goa", name: "Miles", slug: "miles", description: "Bourbon, honey, lemon, smoked salt. Kind of Blue.", price_inr: 950, base_spirit: "bourbon", flavor_tags: ["smoky","sweet","tart"], ingredients: [], image_url: null, is_signature: false },
  { id: "c13f", venue_id: "v19", venue_slug: "for-the-record-goa", name: "33 RPM", slug: "33-rpm", description: "Sake, cucumber, lime, tonic. Long, slow, played at 33.", price_inr: 850, base_spirit: "sake", flavor_tags: ["crisp","refreshing","clean"], ingredients: [], image_url: null, is_signature: false },
  { id: "c13g", venue_id: "v19", venue_slug: "for-the-record-goa", name: "Liner Notes", slug: "liner-notes", description: "Aged rum, demerara, angostura. Nothing flashy. The classic.", price_inr: 900, base_spirit: "rum", flavor_tags: ["boozy","sweet","aromatic"], ingredients: [], image_url: null, is_signature: false },
  { id: "c13h", venue_id: "v19", venue_slug: "for-the-record-goa", name: "Encore", slug: "encore", description: "Cognac, calvados, maple. For when you don't want to leave.", price_inr: 1100, base_spirit: "cognac", flavor_tags: ["rich","sweet","boozy"], ingredients: [], image_url: null, is_signature: false },

  // ===== SOKA MUMBAI (10 drinks) =====
  { id: "c15", venue_id: "v2", venue_slug: "soka-mumbai", name: "Omakase No. 1", slug: "omakase-no-1", description: "No description. Tell the bartender what you feel like.", price_inr: 1200, base_spirit: "varies", flavor_tags: ["seasonal","personal"], ingredients: [], image_url: null, is_signature: true },
  { id: "c15a", venue_id: "v2", venue_slug: "soka-mumbai", name: "Hojicha Sour", slug: "hojicha-sour", description: "Hojicha-infused whisky, lemon, honey, aquafaba.", price_inr: 1100, base_spirit: "whisky", flavor_tags: ["aromatic","silky","sweet"], ingredients: [], image_url: null, is_signature: false },
  { id: "c15b", venue_id: "v2", venue_slug: "soka-mumbai", name: "Suntory Highball", slug: "suntory-highball", description: "Toki whisky, soda, single carved ice. The simplest perfection.", price_inr: 1300, base_spirit: "whisky", flavor_tags: ["crisp","refreshing","clean"], ingredients: [], image_url: null, is_signature: false },
  { id: "c15c", venue_id: "v2", venue_slug: "soka-mumbai", name: "Bandra Sake", slug: "bandra-sake", description: "Junmai sake, cucumber, kaffir lime. Local meets imperial.", price_inr: 1000, base_spirit: "sake", flavor_tags: ["crisp","clean","floral"], ingredients: [], image_url: null, is_signature: false },
  { id: "c15d", venue_id: "v2", venue_slug: "soka-mumbai", name: "Yuzu Spritz", slug: "yuzu-spritz", description: "Gin, yuzu cordial, prosecco, lemon zest.", price_inr: 1100, base_spirit: "gin", flavor_tags: ["citrus","floral","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "c15e", venue_id: "v2", venue_slug: "soka-mumbai", name: "Wasabi Mary", slug: "wasabi-mary", description: "Vodka, tomato, wasabi, soy. Bloody Mary, hard reset.", price_inr: 1000, base_spirit: "vodka", flavor_tags: ["spicy","savory","umami"], ingredients: [], image_url: null, is_signature: false },
  { id: "c15f", venue_id: "v2", venue_slug: "soka-mumbai", name: "Plum Sour", slug: "plum-sour", description: "Bourbon, ume plum, lemon, egg white.", price_inr: 1200, base_spirit: "bourbon", flavor_tags: ["tart","sweet","silky"], ingredients: [], image_url: null, is_signature: false },
  { id: "c15g", venue_id: "v2", venue_slug: "soka-mumbai", name: "Matcha Negroni", slug: "matcha-negroni", description: "Matcha-infused gin, sweet vermouth, Suze.", price_inr: 1300, base_spirit: "gin", flavor_tags: ["bitter","earthy","aromatic"], ingredients: [], image_url: null, is_signature: false },
  { id: "c15h", venue_id: "v2", venue_slug: "soka-mumbai", name: "Shochu Sour", slug: "shochu-sour", description: "Sweet potato shochu, lime, honey, soda.", price_inr: 950, base_spirit: "shochu", flavor_tags: ["earthy","tart","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "c15i", venue_id: "v2", venue_slug: "soka-mumbai", name: "Final Form", slug: "final-form", description: "Aged Japanese whisky, single rock. The bartender's choice ending.", price_inr: 1500, base_spirit: "whisky", flavor_tags: ["boozy","rich","oaky"], ingredients: [], image_url: null, is_signature: false },

  // ===== PERMIT ROOM BANGALORE (10 drinks) =====
  { id: "c16", venue_id: "v13", venue_slug: "permit-room-bangalore", name: "Arrack Sour", slug: "arrack-sour", description: "Kerala coconut arrack, palm jaggery, lime, curry leaf bitters.", price_inr: 600, base_spirit: "arrack", flavor_tags: ["funky","tropical","local"], ingredients: [], image_url: null, is_signature: true },
  { id: "c17", venue_id: "v13", venue_slug: "permit-room-bangalore", name: "Mysore Pak Flip", slug: "mysore-pak-flip", description: "Dark rum, mysore pak-infused milk, nutmeg.", price_inr: 700, base_spirit: "rum", flavor_tags: ["sweet","rich","creamy"], ingredients: [], image_url: null, is_signature: true },
  { id: "c16a", venue_id: "v13", venue_slug: "permit-room-bangalore", name: "Filter Coffee Old Fashioned", slug: "filter-coffee-of", description: "Bourbon, filter coffee reduction, jaggery.", price_inr: 700, base_spirit: "bourbon", flavor_tags: ["bitter","rich","sweet"], ingredients: [], image_url: null, is_signature: false },
  { id: "c16b", venue_id: "v13", venue_slug: "permit-room-bangalore", name: "Toddy Highball", slug: "toddy-highball-pr", description: "Fresh palm toddy, soda, lime. Funky, fast, alive.", price_inr: 500, base_spirit: "toddy", flavor_tags: ["funky","refreshing","local"], ingredients: [], image_url: null, is_signature: false },
  { id: "c16c", venue_id: "v13", venue_slug: "permit-room-bangalore", name: "Kashmiri Mule", slug: "kashmiri-mule", description: "Vodka, kashmiri chili ginger beer, lime.", price_inr: 650, base_spirit: "vodka", flavor_tags: ["spicy","refreshing","tart"], ingredients: [], image_url: null, is_signature: false },
  { id: "c16d", venue_id: "v13", venue_slug: "permit-room-bangalore", name: "Tender Coconut Daiquiri", slug: "tender-coconut-daiquiri", description: "White rum, tender coconut water, lime, sugar.", price_inr: 600, base_spirit: "rum", flavor_tags: ["tropical","refreshing","sweet"], ingredients: [], image_url: null, is_signature: false },
  { id: "c16e", venue_id: "v13", venue_slug: "permit-room-bangalore", name: "Madras Mule", slug: "madras-mule", description: "Arrack, ginger beer, lime, curry leaves.", price_inr: 600, base_spirit: "arrack", flavor_tags: ["spicy","tropical","local"], ingredients: [], image_url: null, is_signature: false },
  { id: "c16f", venue_id: "v13", venue_slug: "permit-room-bangalore", name: "Banglur Negroni", slug: "banglur-negroni", description: "Gin, sweet vermouth, Aperol, curry leaf oil.", price_inr: 750, base_spirit: "gin", flavor_tags: ["bitter","herbal","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "c16g", venue_id: "v13", venue_slug: "permit-room-bangalore", name: "Rava Idli Cocktail", slug: "rava-idli", description: "Whisky, sambhar broth syrup, lime. Yes, breakfast.", price_inr: 700, base_spirit: "whisky", flavor_tags: ["savory","tart","spicy"], ingredients: [], image_url: null, is_signature: false },
  { id: "c16h", venue_id: "v13", venue_slug: "permit-room-bangalore", name: "Sandalwood Sour", slug: "sandalwood-sour", description: "Sandalwood-infused gin, honey, lemon, aquafaba.", price_inr: 850, base_spirit: "gin", flavor_tags: ["floral","sweet","aromatic"], ingredients: [], image_url: null, is_signature: false },

  // ===== MOONSHINE PROJECT HYDERABAD (10 drinks) =====
  { id: "c18", venue_id: "v23", venue_slug: "moonshine-project-hyd", name: "Irani Negroni", slug: "irani-negroni", description: "Gin, sweet vermouth, Campari, cardamom, saffron. Irani cafe in a glass.", price_inr: 800, base_spirit: "gin", flavor_tags: ["bitter","aromatic","complex"], ingredients: [], image_url: null, is_signature: true },
  { id: "c18a", venue_id: "v23", venue_slug: "moonshine-project-hyd", name: "Old Monk Old Fashioned", slug: "old-monk-of", description: "Old Monk reduction, demerara, angostura. Off-menu, ask for it.", price_inr: 750, base_spirit: "rum", flavor_tags: ["sweet","rich","boozy"], ingredients: [], image_url: null, is_signature: false },
  { id: "c18b", venue_id: "v23", venue_slug: "moonshine-project-hyd", name: "Charminar Sour", slug: "charminar-sour", description: "Whisky, jaggery, lime, smoke.", price_inr: 750, base_spirit: "whisky", flavor_tags: ["smoky","tart","sweet"], ingredients: [], image_url: null, is_signature: false },
  { id: "c18c", venue_id: "v23", venue_slug: "moonshine-project-hyd", name: "Hyderabadi Haleem", slug: "hyd-haleem", description: "Spiced rum, dates, almonds, cinnamon. Bowl of haleem, distilled.", price_inr: 850, base_spirit: "rum", flavor_tags: ["spiced","sweet","rich"], ingredients: [], image_url: null, is_signature: false },
  { id: "c18d", venue_id: "v23", venue_slug: "moonshine-project-hyd", name: "Saffron Spritz", slug: "saffron-spritz", description: "Gin, saffron cordial, prosecco, lemon.", price_inr: 800, base_spirit: "gin", flavor_tags: ["floral","aromatic","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "c18e", venue_id: "v23", venue_slug: "moonshine-project-hyd", name: "Tunday Margarita", slug: "tunday-margarita", description: "Tequila, smoked masala syrup, lime.", price_inr: 750, base_spirit: "tequila", flavor_tags: ["smoky","spicy","tart"], ingredients: [], image_url: null, is_signature: false },
  { id: "c18f", venue_id: "v23", venue_slug: "moonshine-project-hyd", name: "Rose Falooda Fizz", slug: "rose-falooda-fizz", description: "Vodka, rose, vermicelli, soda.", price_inr: 700, base_spirit: "vodka", flavor_tags: ["floral","sweet","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "c18g", venue_id: "v23", venue_slug: "moonshine-project-hyd", name: "Biryani Bourbon", slug: "biryani-bourbon", description: "Saffron-infused bourbon, ghee wash, cardamom bitters. Trust the process.", price_inr: 1000, base_spirit: "bourbon", flavor_tags: ["aromatic","rich","spiced"], ingredients: [], image_url: null, is_signature: false },
  { id: "c18h", venue_id: "v23", venue_slug: "moonshine-project-hyd", name: "Pearl City", slug: "pearl-city", description: "Gin, white tea, jasmine, lime. Light, elegant.", price_inr: 800, base_spirit: "gin", flavor_tags: ["floral","crisp","aromatic"], ingredients: [], image_url: null, is_signature: false },
  { id: "c18i", venue_id: "v23", venue_slug: "moonshine-project-hyd", name: "Nizami", slug: "nizami", description: "Cognac, dates, rose, cardamom. Royalty in a coupe.", price_inr: 1100, base_spirit: "cognac", flavor_tags: ["rich","floral","spiced"], ingredients: [], image_url: null, is_signature: false },

  // ===== O PEDRO MUMBAI (8 drinks) =====
  { id: "co1", venue_id: "v3", venue_slug: "o-pedro-mumbai", name: "Pedro's Negroni", slug: "pedros-negroni", description: "Cashew feni, sweet vermouth, Campari. Goa-Italy summit.", price_inr: 850, base_spirit: "feni", flavor_tags: ["bitter","tropical","rich"], ingredients: [], image_url: null, is_signature: true },
  { id: "co2", venue_id: "v3", venue_slug: "o-pedro-mumbai", name: "Sao Tome", slug: "sao-tome", description: "White rum, kokum, lime, mint, soda.", price_inr: 700, base_spirit: "rum", flavor_tags: ["tart","tropical","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "co3", venue_id: "v3", venue_slug: "o-pedro-mumbai", name: "Coastal Mary", slug: "coastal-mary", description: "Vodka, coconut milk, kokum, chili, salt.", price_inr: 750, base_spirit: "vodka", flavor_tags: ["coconut","spicy","tart"], ingredients: [], image_url: null, is_signature: false },
  { id: "co4", venue_id: "v3", venue_slug: "o-pedro-mumbai", name: "Bambolim Sour", slug: "bambolim-sour", description: "Coconut feni, lime, jaggery, aquafaba.", price_inr: 700, base_spirit: "feni", flavor_tags: ["tropical","tart","silky"], ingredients: [], image_url: null, is_signature: false },
  { id: "co5", venue_id: "v3", venue_slug: "o-pedro-mumbai", name: "Vasco Spritz", slug: "vasco-spritz", description: "Aperol, prosecco, kokum, soda.", price_inr: 800, base_spirit: "aperol", flavor_tags: ["bitter","tart","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "co6", venue_id: "v3", venue_slug: "o-pedro-mumbai", name: "Caju Caipirinha", slug: "caju-caipirinha", description: "Cashew feni, jaggery, lime.", price_inr: 650, base_spirit: "feni", flavor_tags: ["tart","sweet","tropical"], ingredients: [], image_url: null, is_signature: false },
  { id: "co7", venue_id: "v3", venue_slug: "o-pedro-mumbai", name: "Praia Punch", slug: "praia-punch", description: "Dark rum, pineapple, lime, jaggery.", price_inr: 750, base_spirit: "rum", flavor_tags: ["tropical","sweet","fruity"], ingredients: [], image_url: null, is_signature: false },
  { id: "co8", venue_id: "v3", venue_slug: "o-pedro-mumbai", name: "Goan Mojito", slug: "goan-mojito", description: "Cashew feni, mint, lime, sugar, soda.", price_inr: 650, base_spirit: "feni", flavor_tags: ["herbal","refreshing","tropical"], ingredients: [], image_url: null, is_signature: false },

  // ===== OTHER VENUES (smaller menus, 8 drinks each for the rest) =====
  // SLINK & BARDOT
  { id: "cs1", venue_id: "v4", venue_slug: "slink-bardot-mumbai", name: "French 75", slug: "french-75", description: "Gin, lemon, sugar, champagne. The classic, perfectly executed.", price_inr: 1200, base_spirit: "gin", flavor_tags: ["citrus","crisp","celebratory"], ingredients: [], image_url: null, is_signature: true },
  { id: "cs2", venue_id: "v4", venue_slug: "slink-bardot-mumbai", name: "Cabaret", slug: "cabaret", description: "Cognac, absinthe, sweet vermouth, bitters.", price_inr: 1300, base_spirit: "cognac", flavor_tags: ["herbal","boozy","aromatic"], ingredients: [], image_url: null, is_signature: false },
  { id: "cs3", venue_id: "v4", venue_slug: "slink-bardot-mumbai", name: "Bardot Martini", slug: "bardot-martini", description: "Vodka, dry vermouth, lemon, olive.", price_inr: 1100, base_spirit: "vodka", flavor_tags: ["crisp","savory","boozy"], ingredients: [], image_url: null, is_signature: false },
  { id: "cs4", venue_id: "v4", venue_slug: "slink-bardot-mumbai", name: "Velvet Curtain", slug: "velvet-curtain", description: "Red wine, cognac, blackberry, vanilla.", price_inr: 1200, base_spirit: "wine", flavor_tags: ["rich","fruity","sweet"], ingredients: [], image_url: null, is_signature: false },
  { id: "cs5", venue_id: "v4", venue_slug: "slink-bardot-mumbai", name: "Worli Sunset", slug: "worli-sunset", description: "Tequila, blood orange, lime, agave.", price_inr: 950, base_spirit: "tequila", flavor_tags: ["citrus","sweet","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "cs6", venue_id: "v4", venue_slug: "slink-bardot-mumbai", name: "Burlesque", slug: "burlesque", description: "Champagne, hibiscus, gin, lemon.", price_inr: 1400, base_spirit: "gin", flavor_tags: ["floral","crisp","celebratory"], ingredients: [], image_url: null, is_signature: false },
  { id: "cs7", venue_id: "v4", venue_slug: "slink-bardot-mumbai", name: "Cigar Lounge", slug: "cigar-lounge", description: "Cognac, dark chocolate bitters, smoked salt.", price_inr: 1500, base_spirit: "cognac", flavor_tags: ["smoky","rich","boozy"], ingredients: [], image_url: null, is_signature: false },
  { id: "cs8", venue_id: "v4", venue_slug: "slink-bardot-mumbai", name: "1920", slug: "1920", description: "Rye, sweet vermouth, absinthe rinse.", price_inr: 1300, base_spirit: "rye", flavor_tags: ["herbal","boozy","aromatic"], ingredients: [], image_url: null, is_signature: false },

  // AMERICANO
  { id: "ca1", venue_id: "v5", venue_slug: "americano-mumbai", name: "Americano", slug: "americano-classic", description: "Campari, sweet vermouth, soda. The aperitivo, perfectly built.", price_inr: 700, base_spirit: "campari", flavor_tags: ["bitter","refreshing","crisp"], ingredients: [], image_url: null, is_signature: true },
  { id: "ca2", venue_id: "v5", venue_slug: "americano-mumbai", name: "Negroni Sbagliato", slug: "negroni-sbagliato", description: "Campari, sweet vermouth, prosecco. With prosecco. So good.", price_inr: 850, base_spirit: "campari", flavor_tags: ["bitter","crisp","celebratory"], ingredients: [], image_url: null, is_signature: false },
  { id: "ca3", venue_id: "v5", venue_slug: "americano-mumbai", name: "Boulevardier", slug: "boulevardier", description: "Bourbon, sweet vermouth, Campari. The whisky Negroni.", price_inr: 950, base_spirit: "bourbon", flavor_tags: ["bitter","rich","boozy"], ingredients: [], image_url: null, is_signature: false },
  { id: "ca4", venue_id: "v5", venue_slug: "americano-mumbai", name: "Aperol Spritz", slug: "aperol-spritz", description: "Aperol, prosecco, soda, orange.", price_inr: 800, base_spirit: "aperol", flavor_tags: ["bitter","refreshing","celebratory"], ingredients: [], image_url: null, is_signature: false },
  { id: "ca5", venue_id: "v5", venue_slug: "americano-mumbai", name: "Garibaldi", slug: "garibaldi", description: "Campari, fresh orange juice. Two ingredients, life-changing.", price_inr: 700, base_spirit: "campari", flavor_tags: ["bitter","citrus","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "ca6", venue_id: "v5", venue_slug: "americano-mumbai", name: "Hugo", slug: "hugo", description: "Elderflower, prosecco, mint, lime, soda.", price_inr: 800, base_spirit: "elderflower", flavor_tags: ["floral","crisp","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "ca7", venue_id: "v5", venue_slug: "americano-mumbai", name: "Bicicletta", slug: "bicicletta", description: "Campari, white wine, soda. Light, dry, perfect.", price_inr: 750, base_spirit: "campari", flavor_tags: ["bitter","crisp","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "ca8", venue_id: "v5", venue_slug: "americano-mumbai", name: "Cynar Spritz", slug: "cynar-spritz", description: "Cynar, prosecco, soda, orange. Artichoke aperitivo. Trust.", price_inr: 850, base_spirit: "cynar", flavor_tags: ["bitter","earthy","refreshing"], ingredients: [], image_url: null, is_signature: false },

  // BASTIAN OBEROI MUMBAI
  { id: "cb1", venue_id: "v6", venue_slug: "bastian-oberoi-mumbai", name: "Oberoi Martini", slug: "oberoi-martini", description: "Gin, dry vermouth, citrus oil. Served from the trolley.", price_inr: 1500, base_spirit: "gin", flavor_tags: ["crisp","boozy","aromatic"], ingredients: [], image_url: null, is_signature: true },
  { id: "cb2", venue_id: "v6", venue_slug: "bastian-oberoi-mumbai", name: "Harbor Sour", slug: "harbor-sour", description: "Whisky, lemon, honey, sea salt.", price_inr: 1100, base_spirit: "whisky", flavor_tags: ["tart","sweet","savory"], ingredients: [], image_url: null, is_signature: false },
  { id: "cb3", venue_id: "v6", venue_slug: "bastian-oberoi-mumbai", name: "Marine Drive", slug: "marine-drive", description: "Vodka, sea salt, lime, kokum.", price_inr: 950, base_spirit: "vodka", flavor_tags: ["savory","tart","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "cb4", venue_id: "v6", venue_slug: "bastian-oberoi-mumbai", name: "Champagne Saber", slug: "champagne-saber", description: "Champagne, gin, lavender, lemon.", price_inr: 1800, base_spirit: "champagne", flavor_tags: ["floral","crisp","celebratory"], ingredients: [], image_url: null, is_signature: false },
  { id: "cb5", venue_id: "v6", venue_slug: "bastian-oberoi-mumbai", name: "Nariman", slug: "nariman", description: "Cognac, port, dark chocolate.", price_inr: 1400, base_spirit: "cognac", flavor_tags: ["rich","sweet","boozy"], ingredients: [], image_url: null, is_signature: false },
  { id: "cb6", venue_id: "v6", venue_slug: "bastian-oberoi-mumbai", name: "Bastian Negroni", slug: "bastian-negroni", description: "Gin, sweet vermouth, Campari, smoked orange.", price_inr: 1100, base_spirit: "gin", flavor_tags: ["bitter","smoky","aromatic"], ingredients: [], image_url: null, is_signature: false },
  { id: "cb7", venue_id: "v6", venue_slug: "bastian-oberoi-mumbai", name: "Pearl Diver", slug: "pearl-diver", description: "Aged rum, butter syrup, citrus, allspice.", price_inr: 1200, base_spirit: "rum", flavor_tags: ["tropical","rich","spiced"], ingredients: [], image_url: null, is_signature: false },
  { id: "cb8", venue_id: "v6", venue_slug: "bastian-oberoi-mumbai", name: "Silver Service", slug: "silver-service", description: "Vodka, elderflower, cucumber, prosecco.", price_inr: 1100, base_spirit: "vodka", flavor_tags: ["floral","crisp","refreshing"], ingredients: [], image_url: null, is_signature: false },

  // LAIR DELHI
  { id: "cl1", venue_id: "v9", venue_slug: "lair-delhi", name: "After Hours", slug: "after-hours", description: "Mezcal, smoked paprika, lime, agave. After 11pm only.", price_inr: 1200, base_spirit: "mezcal", flavor_tags: ["smoky","spicy","tart"], ingredients: [], image_url: null, is_signature: true },
  { id: "cl2", venue_id: "v9", venue_slug: "lair-delhi", name: "Black Door", slug: "black-door", description: "Activated charcoal gin, blackberry, lime.", price_inr: 1100, base_spirit: "gin", flavor_tags: ["earthy","tart","fruity"], ingredients: [], image_url: null, is_signature: false },
  { id: "cl3", venue_id: "v9", venue_slug: "lair-delhi", name: "Silent", slug: "silent", description: "White rum, white tea, white pepper, lime.", price_inr: 1000, base_spirit: "rum", flavor_tags: ["aromatic","crisp","clean"], ingredients: [], image_url: null, is_signature: false },
  { id: "cl4", venue_id: "v9", venue_slug: "lair-delhi", name: "Ringer", slug: "ringer", description: "Bourbon, honey, lemon, smoke.", price_inr: 1100, base_spirit: "bourbon", flavor_tags: ["smoky","sweet","tart"], ingredients: [], image_url: null, is_signature: false },
  { id: "cl5", venue_id: "v9", venue_slug: "lair-delhi", name: "Andaz", slug: "andaz", description: "Vodka, cardamom, rose, lime.", price_inr: 950, base_spirit: "vodka", flavor_tags: ["floral","spiced","tart"], ingredients: [], image_url: null, is_signature: false },
  { id: "cl6", venue_id: "v9", venue_slug: "lair-delhi", name: "Aerocity", slug: "aerocity", description: "Tequila, jalapeño, pineapple, lime.", price_inr: 1050, base_spirit: "tequila", flavor_tags: ["spicy","tropical","tart"], ingredients: [], image_url: null, is_signature: false },
  { id: "cl7", venue_id: "v9", venue_slug: "lair-delhi", name: "12 Seats", slug: "12-seats", description: "Cognac, port, orange peel.", price_inr: 1300, base_spirit: "cognac", flavor_tags: ["rich","sweet","boozy"], ingredients: [], image_url: null, is_signature: false },
  { id: "cl8", venue_id: "v9", venue_slug: "lair-delhi", name: "Last Call", slug: "last-call", description: "Aged rum, demerara, angostura, smoke.", price_inr: 1200, base_spirit: "rum", flavor_tags: ["smoky","sweet","boozy"], ingredients: [], image_url: null, is_signature: false },

  // ZLB 23
  { id: "cz1", venue_id: "v11", venue_slug: "zlb-23-delhi", name: "Room 23", slug: "room-23", description: "Vodka, dry vermouth, olive brine, lemon. Cold and stiff.", price_inr: 1300, base_spirit: "vodka", flavor_tags: ["savory","crisp","boozy"], ingredients: [], image_url: null, is_signature: true },
  { id: "cz2", venue_id: "v11", venue_slug: "zlb-23-delhi", name: "Saxophone", slug: "saxophone", description: "Bourbon, sweet vermouth, bitters, cherry.", price_inr: 1200, base_spirit: "bourbon", flavor_tags: ["boozy","sweet","aromatic"], ingredients: [], image_url: null, is_signature: false },
  { id: "cz3", venue_id: "v11", venue_slug: "zlb-23-delhi", name: "Brass", slug: "brass", description: "Whisky, honey, lemon, ginger.", price_inr: 1100, base_spirit: "whisky", flavor_tags: ["warming","sweet","tart"], ingredients: [], image_url: null, is_signature: false },
  { id: "cz4", venue_id: "v11", venue_slug: "zlb-23-delhi", name: "Improvisation", slug: "improvisation", description: "Bartender's choice. Tell them what you like.", price_inr: 1400, base_spirit: "varies", flavor_tags: ["seasonal","personal"], ingredients: [], image_url: null, is_signature: false },
  { id: "cz5", venue_id: "v11", venue_slug: "zlb-23-delhi", name: "Quartet", slug: "quartet", description: "Gin, Lillet, lemon, absinthe.", price_inr: 1300, base_spirit: "gin", flavor_tags: ["herbal","crisp","boozy"], ingredients: [], image_url: null, is_signature: false },
  { id: "cz6", venue_id: "v11", venue_slug: "zlb-23-delhi", name: "Vinyl", slug: "vinyl-zlb", description: "Aged rum, demerara, angostura.", price_inr: 1100, base_spirit: "rum", flavor_tags: ["sweet","boozy","aromatic"], ingredients: [], image_url: null, is_signature: false },
  { id: "cz7", venue_id: "v11", venue_slug: "zlb-23-delhi", name: "Scotch and Soda", slug: "scotch-soda", description: "Single malt, soda, single rock. Done well.", price_inr: 1500, base_spirit: "whisky", flavor_tags: ["crisp","boozy","clean"], ingredients: [], image_url: null, is_signature: false },
  { id: "cz8", venue_id: "v11", venue_slug: "zlb-23-delhi", name: "Encore Note", slug: "encore-note", description: "Cognac, calvados, maple, lemon.", price_inr: 1300, base_spirit: "cognac", flavor_tags: ["rich","sweet","boozy"], ingredients: [], image_url: null, is_signature: false },

  // CIRRUS 9
  { id: "cc1", venue_id: "v14", venue_slug: "cirrus-9-bangalore", name: "Cirrus", slug: "cirrus", description: "Gin, elderflower, cucumber, prosecco.", price_inr: 950, base_spirit: "gin", flavor_tags: ["floral","crisp","refreshing"], ingredients: [], image_url: null, is_signature: true },
  { id: "cc2", venue_id: "v14", venue_slug: "cirrus-9-bangalore", name: "Sky Bar", slug: "sky-bar", description: "Whisky, peach, lemon, soda.", price_inr: 1000, base_spirit: "whisky", flavor_tags: ["fruity","tart","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "cc3", venue_id: "v14", venue_slug: "cirrus-9-bangalore", name: "9th Floor", slug: "9th-floor", description: "Gin, blue curacao, lime, tonic.", price_inr: 950, base_spirit: "gin", flavor_tags: ["citrus","crisp","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "cc4", venue_id: "v14", venue_slug: "cirrus-9-bangalore", name: "Sunset Sour", slug: "sunset-sour", description: "Bourbon, blood orange, lemon, honey.", price_inr: 950, base_spirit: "bourbon", flavor_tags: ["citrus","sweet","tart"], ingredients: [], image_url: null, is_signature: false },
  { id: "cc5", venue_id: "v14", venue_slug: "cirrus-9-bangalore", name: "Highline", slug: "highline", description: "Vodka, watermelon, lime, basil.", price_inr: 900, base_spirit: "vodka", flavor_tags: ["fruity","herbal","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "cc6", venue_id: "v14", venue_slug: "cirrus-9-bangalore", name: "Whisky Trail", slug: "whisky-trail", description: "Single malt, bitters, demerara, smoke.", price_inr: 1300, base_spirit: "whisky", flavor_tags: ["smoky","boozy","rich"], ingredients: [], image_url: null, is_signature: false },
  { id: "cc7", venue_id: "v14", venue_slug: "cirrus-9-bangalore", name: "Garden Spritz", slug: "garden-spritz", description: "Aperol, prosecco, basil, soda.", price_inr: 850, base_spirit: "aperol", flavor_tags: ["bitter","herbal","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "cc8", venue_id: "v14", venue_slug: "cirrus-9-bangalore", name: "Cloud Nine", slug: "cloud-nine", description: "Gin, lavender, lemon, tonic.", price_inr: 900, base_spirit: "gin", flavor_tags: ["floral","crisp","refreshing"], ingredients: [], image_url: null, is_signature: false },

  // BASTIAN BLR
  { id: "cbb1", venue_id: "v15", venue_slug: "bastian-oberoi-blr", name: "Orchid Martini", slug: "orchid-martini", description: "Gin, vanilla orchid syrup, citrus, prosecco. The signature.", price_inr: 1200, base_spirit: "gin", flavor_tags: ["floral","crisp","celebratory"], ingredients: [], image_url: null, is_signature: true },
  { id: "cbb2", venue_id: "v15", venue_slug: "bastian-oberoi-blr", name: "Green Velvet", slug: "green-velvet", description: "Vodka, matcha, lime, prosecco.", price_inr: 1100, base_spirit: "vodka", flavor_tags: ["earthy","crisp","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "cbb3", venue_id: "v15", venue_slug: "bastian-oberoi-blr", name: "Brass Cuff", slug: "brass-cuff", description: "Bourbon, honey, lemon, ginger.", price_inr: 1000, base_spirit: "bourbon", flavor_tags: ["warming","sweet","tart"], ingredients: [], image_url: null, is_signature: false },
  { id: "cbb4", venue_id: "v15", venue_slug: "bastian-oberoi-blr", name: "Raw Bar", slug: "raw-bar", description: "Vodka, oyster brine, lime, sea salt.", price_inr: 950, base_spirit: "vodka", flavor_tags: ["savory","umami","crisp"], ingredients: [], image_url: null, is_signature: false },
  { id: "cbb5", venue_id: "v15", venue_slug: "bastian-oberoi-blr", name: "Champagne Cocktail", slug: "champagne-cocktail", description: "Champagne, sugar, bitters, lemon twist.", price_inr: 1500, base_spirit: "champagne", flavor_tags: ["crisp","celebratory","aromatic"], ingredients: [], image_url: null, is_signature: false },
  { id: "cbb6", venue_id: "v15", venue_slug: "bastian-oberoi-blr", name: "Glam Sour", slug: "glam-sour", description: "Whisky, hibiscus, lemon, aquafaba.", price_inr: 1100, base_spirit: "whisky", flavor_tags: ["floral","tart","silky"], ingredients: [], image_url: null, is_signature: false },
  { id: "cbb7", venue_id: "v15", venue_slug: "bastian-oberoi-blr", name: "Brass Lounge", slug: "brass-lounge", description: "Cognac, dark chocolate, orange, smoke.", price_inr: 1400, base_spirit: "cognac", flavor_tags: ["rich","smoky","sweet"], ingredients: [], image_url: null, is_signature: false },
  { id: "cbb8", venue_id: "v15", venue_slug: "bastian-oberoi-blr", name: "Velvet Negroni", slug: "velvet-negroni-blr", description: "Gin, sweet vermouth, Campari, vanilla.", price_inr: 1100, base_spirit: "gin", flavor_tags: ["bitter","sweet","aromatic"], ingredients: [], image_url: null, is_signature: false },

  // TOCA
  { id: "ct1", venue_id: "v16", venue_slug: "toca-rooftop-blr", name: "Toca Spritz", slug: "toca-spritz", description: "Aperol, prosecco, soda, orange.", price_inr: 750, base_spirit: "aperol", flavor_tags: ["bitter","refreshing","celebratory"], ingredients: [], image_url: null, is_signature: true },
  { id: "ct2", venue_id: "v16", venue_slug: "toca-rooftop-blr", name: "Vittal Margarita", slug: "vittal-margarita", description: "Tequila, lime, agave, salt.", price_inr: 700, base_spirit: "tequila", flavor_tags: ["citrus","tart","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "ct3", venue_id: "v16", venue_slug: "toca-rooftop-blr", name: "Friday Mule", slug: "friday-mule", description: "Vodka, ginger beer, lime.", price_inr: 650, base_spirit: "vodka", flavor_tags: ["spicy","refreshing","tart"], ingredients: [], image_url: null, is_signature: false },
  { id: "ct4", venue_id: "v16", venue_slug: "toca-rooftop-blr", name: "Rooftop Mojito", slug: "rooftop-mojito", description: "White rum, mint, lime, sugar, soda.", price_inr: 650, base_spirit: "rum", flavor_tags: ["herbal","refreshing","tart"], ingredients: [], image_url: null, is_signature: false },
  { id: "ct5", venue_id: "v16", venue_slug: "toca-rooftop-blr", name: "Sky Sour", slug: "sky-sour", description: "Whisky, lemon, honey, egg white.", price_inr: 750, base_spirit: "whisky", flavor_tags: ["tart","sweet","silky"], ingredients: [], image_url: null, is_signature: false },
  { id: "ct6", venue_id: "v16", venue_slug: "toca-rooftop-blr", name: "Pink Gin", slug: "pink-gin-toca", description: "Gin, rose syrup, tonic, lime.", price_inr: 700, base_spirit: "gin", flavor_tags: ["floral","crisp","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "ct7", venue_id: "v16", venue_slug: "toca-rooftop-blr", name: "Long Island", slug: "long-island", description: "Five spirits, lemon, cola.", price_inr: 850, base_spirit: "varies", flavor_tags: ["boozy","strong","sweet"], ingredients: [], image_url: null, is_signature: false },
  { id: "ct8", venue_id: "v16", venue_slug: "toca-rooftop-blr", name: "Garden Gimlet", slug: "garden-gimlet", description: "Gin, cucumber, lime, basil.", price_inr: 700, base_spirit: "gin", flavor_tags: ["herbal","crisp","refreshing"], ingredients: [], image_url: null, is_signature: false },

  // PLAN B
  { id: "cp1", venue_id: "v17", venue_slug: "plan-b-loaded-blr", name: "Plan B Sangria", slug: "plan-b-sangria", description: "Red wine, fruit, brandy. By the pitcher.", price_inr: 600, base_spirit: "wine", flavor_tags: ["fruity","sweet","casual"], ingredients: [], image_url: null, is_signature: true },
  { id: "cp2", venue_id: "v17", venue_slug: "plan-b-loaded-blr", name: "12th Main Mule", slug: "12th-main-mule", description: "Vodka, ginger beer, lime.", price_inr: 450, base_spirit: "vodka", flavor_tags: ["spicy","tart","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "cp3", venue_id: "v17", venue_slug: "plan-b-loaded-blr", name: "Loaded LIIT", slug: "loaded-liit", description: "Five spirits, citrus, cola. Stronger than your last relationship.", price_inr: 550, base_spirit: "varies", flavor_tags: ["boozy","strong","sweet"], ingredients: [], image_url: null, is_signature: false },
  { id: "cp4", venue_id: "v17", venue_slug: "plan-b-loaded-blr", name: "Indiranagar Mojito", slug: "indiranagar-mojito", description: "Rum, mint, lime, soda.", price_inr: 450, base_spirit: "rum", flavor_tags: ["herbal","refreshing","tart"], ingredients: [], image_url: null, is_signature: false },
  { id: "cp5", venue_id: "v17", venue_slug: "plan-b-loaded-blr", name: "Tequila Sunrise", slug: "tequila-sunrise", description: "Tequila, OJ, grenadine.", price_inr: 500, base_spirit: "tequila", flavor_tags: ["fruity","sweet","casual"], ingredients: [], image_url: null, is_signature: false },
  { id: "cp6", venue_id: "v17", venue_slug: "plan-b-loaded-blr", name: "Sex on the Beach", slug: "sex-on-beach", description: "Vodka, peach, cranberry, OJ.", price_inr: 500, base_spirit: "vodka", flavor_tags: ["fruity","sweet","casual"], ingredients: [], image_url: null, is_signature: false },
  { id: "cp7", venue_id: "v17", venue_slug: "plan-b-loaded-blr", name: "Whisky Ginger", slug: "whisky-ginger", description: "Whisky, ginger ale, lime.", price_inr: 500, base_spirit: "whisky", flavor_tags: ["spicy","crisp","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "cp8", venue_id: "v17", venue_slug: "plan-b-loaded-blr", name: "Beer Tower", slug: "beer-tower", description: "5L of cold beer. For groups. For Saturdays.", price_inr: 1500, base_spirit: "beer", flavor_tags: ["casual","crisp","group"], ingredients: [], image_url: null, is_signature: false },

  // TESOURO
  { id: "cte1", venue_id: "v20", venue_slug: "tesouro-goa", name: "Vinho Verde Spritz", slug: "vinho-verde-spritz", description: "Vinho verde, peach, mint, soda.", price_inr: 700, base_spirit: "wine", flavor_tags: ["fruity","crisp","refreshing"], ingredients: [], image_url: null, is_signature: true },
  { id: "cte2", venue_id: "v20", venue_slug: "tesouro-goa", name: "Parra Negroni", slug: "parra-negroni", description: "Gin, port, Campari.", price_inr: 800, base_spirit: "gin", flavor_tags: ["bitter","rich","aromatic"], ingredients: [], image_url: null, is_signature: false },
  { id: "cte3", venue_id: "v20", venue_slug: "tesouro-goa", name: "Lisbon Lemonade", slug: "lisbon-lemonade", description: "Gin, lemon, tonic, mint.", price_inr: 650, base_spirit: "gin", flavor_tags: ["citrus","crisp","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "cte4", venue_id: "v20", venue_slug: "tesouro-goa", name: "Petisco Sour", slug: "petisco-sour", description: "Madeira, lemon, honey, aquafaba.", price_inr: 750, base_spirit: "madeira", flavor_tags: ["rich","tart","silky"], ingredients: [], image_url: null, is_signature: false },
  { id: "cte5", venue_id: "v20", venue_slug: "tesouro-goa", name: "Blue Door", slug: "blue-door", description: "Vodka, blue curacao, lime, tonic.", price_inr: 650, base_spirit: "vodka", flavor_tags: ["citrus","crisp","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "cte6", venue_id: "v20", venue_slug: "tesouro-goa", name: "Salazar", slug: "salazar", description: "Cognac, port, orange, bitters.", price_inr: 850, base_spirit: "cognac", flavor_tags: ["rich","sweet","aromatic"], ingredients: [], image_url: null, is_signature: false },
  { id: "cte7", venue_id: "v20", venue_slug: "tesouro-goa", name: "Tagus", slug: "tagus", description: "White port, tonic, lemon. Portuguese aperitivo.", price_inr: 700, base_spirit: "port", flavor_tags: ["sweet","crisp","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "cte8", venue_id: "v20", venue_slug: "tesouro-goa", name: "Bacalhau Mary", slug: "bacalhau-mary", description: "Vodka, tomato, peri-peri, lemon.", price_inr: 700, base_spirit: "vodka", flavor_tags: ["spicy","savory","tart"], ingredients: [], image_url: null, is_signature: false },

  // ANTARES
  { id: "can1", venue_id: "v21", venue_slug: "antares-goa", name: "Sunset Spritz", slug: "sunset-spritz", description: "Aperol, prosecco, blood orange. As the sun goes down.", price_inr: 900, base_spirit: "aperol", flavor_tags: ["bitter","citrus","celebratory"], ingredients: [], image_url: null, is_signature: true },
  { id: "can2", venue_id: "v21", venue_slug: "antares-goa", name: "Vagator", slug: "vagator", description: "Mezcal, pineapple, lime, chili.", price_inr: 1000, base_spirit: "mezcal", flavor_tags: ["smoky","tropical","spicy"], ingredients: [], image_url: null, is_signature: false },
  { id: "can3", venue_id: "v21", venue_slug: "antares-goa", name: "Pool Party", slug: "pool-party", description: "Coconut rum, pineapple, lime, mint.", price_inr: 850, base_spirit: "rum", flavor_tags: ["tropical","sweet","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "can4", venue_id: "v21", venue_slug: "antares-goa", name: "Beach Negroni", slug: "beach-negroni", description: "Gin, Aperol, prosecco, lime.", price_inr: 900, base_spirit: "gin", flavor_tags: ["bitter","crisp","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "can5", venue_id: "v21", venue_slug: "antares-goa", name: "DJ Set", slug: "dj-set", description: "Tequila, watermelon, lime, salt.", price_inr: 850, base_spirit: "tequila", flavor_tags: ["fruity","tart","casual"], ingredients: [], image_url: null, is_signature: false },
  { id: "can6", venue_id: "v21", venue_slug: "antares-goa", name: "Cliffside", slug: "cliffside", description: "Vodka, cucumber, lime, soda.", price_inr: 800, base_spirit: "vodka", flavor_tags: ["crisp","refreshing","clean"], ingredients: [], image_url: null, is_signature: false },
  { id: "can7", venue_id: "v21", venue_slug: "antares-goa", name: "Ozran", slug: "ozran", description: "White rum, coconut, lime, basil.", price_inr: 850, base_spirit: "rum", flavor_tags: ["tropical","herbal","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "can8", venue_id: "v21", venue_slug: "antares-goa", name: "Last Set", slug: "last-set", description: "Aged rum, demerara, bitters. For 4am.", price_inr: 1100, base_spirit: "rum", flavor_tags: ["sweet","boozy","aromatic"], ingredients: [], image_url: null, is_signature: false },

  // MOJIGAO
  { id: "cm1", venue_id: "v22", venue_slug: "mojigao-goa", name: "Mezcal Garden", slug: "mezcal-garden", description: "Mezcal, hibiscus, lime, agave.", price_inr: 850, base_spirit: "mezcal", flavor_tags: ["smoky","floral","tart"], ingredients: [], image_url: null, is_signature: true },
  { id: "cm2", venue_id: "v22", venue_slug: "mojigao-goa", name: "Mango Tree", slug: "mango-tree", description: "Mezcal, mango, chili, lime.", price_inr: 800, base_spirit: "mezcal", flavor_tags: ["smoky","tropical","spicy"], ingredients: [], image_url: null, is_signature: false },
  { id: "cm3", venue_id: "v22", venue_slug: "mojigao-goa", name: "Paloma", slug: "paloma", description: "Tequila, grapefruit, lime, salt.", price_inr: 750, base_spirit: "tequila", flavor_tags: ["citrus","refreshing","crisp"], ingredients: [], image_url: null, is_signature: false },
  { id: "cm4", venue_id: "v22", venue_slug: "mojigao-goa", name: "Smoked Margarita", slug: "smoked-margarita", description: "Mezcal, lime, agave, smoked salt.", price_inr: 800, base_spirit: "mezcal", flavor_tags: ["smoky","tart","savory"], ingredients: [], image_url: null, is_signature: false },
  { id: "cm5", venue_id: "v22", venue_slug: "mojigao-goa", name: "Garden Tequila", slug: "garden-tequila", description: "Tequila, basil, lime, cucumber.", price_inr: 750, base_spirit: "tequila", flavor_tags: ["herbal","refreshing","crisp"], ingredients: [], image_url: null, is_signature: false },
  { id: "cm6", venue_id: "v22", venue_slug: "mojigao-goa", name: "Oaxaca", slug: "oaxaca", description: "Mezcal, Aperol, pineapple, lime.", price_inr: 850, base_spirit: "mezcal", flavor_tags: ["smoky","tropical","bitter"], ingredients: [], image_url: null, is_signature: false },
  { id: "cm7", venue_id: "v22", venue_slug: "mojigao-goa", name: "Fairy Light", slug: "fairy-light", description: "Gin, elderflower, lime, prosecco.", price_inr: 900, base_spirit: "gin", flavor_tags: ["floral","crisp","celebratory"], ingredients: [], image_url: null, is_signature: false },
  { id: "cm8", venue_id: "v22", venue_slug: "mojigao-goa", name: "Mango Tree Sour", slug: "mango-tree-sour", description: "Tequila, mango, lime, egg white.", price_inr: 800, base_spirit: "tequila", flavor_tags: ["tropical","tart","silky"], ingredients: [], image_url: null, is_signature: false },

  // OVER THE MOON
  { id: "cot1", venue_id: "v24", venue_slug: "over-the-moon-hyd", name: "Banjara Sunset", slug: "banjara-sunset", description: "Tequila, blood orange, agave, lime.", price_inr: 700, base_spirit: "tequila", flavor_tags: ["citrus","sweet","refreshing"], ingredients: [], image_url: null, is_signature: true },
  { id: "cot2", venue_id: "v24", venue_slug: "over-the-moon-hyd", name: "Pizza Oven", slug: "pizza-oven", description: "Bourbon, smoked paprika, honey, lemon.", price_inr: 800, base_spirit: "bourbon", flavor_tags: ["smoky","sweet","warming"], ingredients: [], image_url: null, is_signature: false },
  { id: "cot3", venue_id: "v24", venue_slug: "over-the-moon-hyd", name: "Skyline", slug: "skyline", description: "Vodka, lychee, elderflower, lime.", price_inr: 750, base_spirit: "vodka", flavor_tags: ["floral","sweet","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "cot4", venue_id: "v24", venue_slug: "over-the-moon-hyd", name: "Hyd Mule", slug: "hyd-mule", description: "Vodka, ginger beer, lime, mint.", price_inr: 650, base_spirit: "vodka", flavor_tags: ["spicy","refreshing","tart"], ingredients: [], image_url: null, is_signature: false },
  { id: "cot5", venue_id: "v24", venue_slug: "over-the-moon-hyd", name: "Crescent", slug: "crescent", description: "Gin, cardamom, lemon, soda.", price_inr: 700, base_spirit: "gin", flavor_tags: ["spiced","crisp","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "cot6", venue_id: "v24", venue_slug: "over-the-moon-hyd", name: "Charminar Spritz", slug: "charminar-spritz", description: "Aperol, prosecco, orange.", price_inr: 750, base_spirit: "aperol", flavor_tags: ["bitter","citrus","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "cot7", venue_id: "v24", venue_slug: "over-the-moon-hyd", name: "Lunar Negroni", slug: "lunar-negroni", description: "Gin, sweet vermouth, Campari.", price_inr: 750, base_spirit: "gin", flavor_tags: ["bitter","rich","aromatic"], ingredients: [], image_url: null, is_signature: false },
  { id: "cot8", venue_id: "v24", venue_slug: "over-the-moon-hyd", name: "Eclipse", slug: "eclipse", description: "Whisky, espresso, demerara, smoke.", price_inr: 850, base_spirit: "whisky", flavor_tags: ["smoky","bitter","rich"], ingredients: [], image_url: null, is_signature: false },

  // ALTITUDE
  { id: "cal1", venue_id: "v25", venue_slug: "altitude-hyd", name: "Classic Martini", slug: "classic-martini-alt", description: "Gin, dry vermouth, olive. Done properly.", price_inr: 800, base_spirit: "gin", flavor_tags: ["crisp","savory","boozy"], ingredients: [], image_url: null, is_signature: true },
  { id: "cal2", venue_id: "v25", venue_slug: "altitude-hyd", name: "Old Fashioned", slug: "old-fashioned-alt", description: "Bourbon, sugar, bitters, orange.", price_inr: 850, base_spirit: "bourbon", flavor_tags: ["boozy","sweet","aromatic"], ingredients: [], image_url: null, is_signature: false },
  { id: "cal3", venue_id: "v25", venue_slug: "altitude-hyd", name: "Manhattan", slug: "manhattan-alt", description: "Rye, sweet vermouth, bitters, cherry.", price_inr: 900, base_spirit: "rye", flavor_tags: ["boozy","sweet","aromatic"], ingredients: [], image_url: null, is_signature: false },
  { id: "cal4", venue_id: "v25", venue_slug: "altitude-hyd", name: "Negroni", slug: "negroni-alt", description: "Gin, sweet vermouth, Campari.", price_inr: 800, base_spirit: "gin", flavor_tags: ["bitter","rich","aromatic"], ingredients: [], image_url: null, is_signature: false },
  { id: "cal5", venue_id: "v25", venue_slug: "altitude-hyd", name: "Sidecar", slug: "sidecar-alt", description: "Cognac, triple sec, lemon.", price_inr: 950, base_spirit: "cognac", flavor_tags: ["citrus","boozy","sweet"], ingredients: [], image_url: null, is_signature: false },
  { id: "cal6", venue_id: "v25", venue_slug: "altitude-hyd", name: "Sazerac", slug: "sazerac", description: "Rye, absinthe rinse, sugar, bitters.", price_inr: 1000, base_spirit: "rye", flavor_tags: ["herbal","boozy","aromatic"], ingredients: [], image_url: null, is_signature: false },
  { id: "cal7", venue_id: "v25", venue_slug: "altitude-hyd", name: "Whisky Sour", slug: "whisky-sour-alt", description: "Whisky, lemon, sugar, egg white.", price_inr: 750, base_spirit: "whisky", flavor_tags: ["tart","sweet","silky"], ingredients: [], image_url: null, is_signature: false },
  { id: "cal8", venue_id: "v25", venue_slug: "altitude-hyd", name: "Daiquiri", slug: "daiquiri-alt", description: "White rum, lime, sugar.", price_inr: 700, base_spirit: "rum", flavor_tags: ["tart","crisp","clean"], ingredients: [], image_url: null, is_signature: false },

  // PREGNANT MAN
  { id: "cpm1", venue_id: "v26", venue_slug: "pregnant-man-pune", name: "Pregnant Man", slug: "pregnant-man", description: "Whisky, kokum, lime, smoked salt.", price_inr: 700, base_spirit: "whisky", flavor_tags: ["smoky","tart","savory"], ingredients: [], image_url: null, is_signature: true },
  { id: "cpm2", venue_id: "v26", venue_slug: "pregnant-man-pune", name: "Lane 7 Sour", slug: "lane-7-sour", description: "Bourbon, lemon, jaggery, aquafaba.", price_inr: 750, base_spirit: "bourbon", flavor_tags: ["tart","sweet","silky"], ingredients: [], image_url: null, is_signature: false },
  { id: "cpm3", venue_id: "v26", venue_slug: "pregnant-man-pune", name: "Koregaon Mule", slug: "koregaon-mule", description: "Vodka, ginger beer, lime, mint.", price_inr: 650, base_spirit: "vodka", flavor_tags: ["spicy","refreshing","tart"], ingredients: [], image_url: null, is_signature: false },
  { id: "cpm4", venue_id: "v26", venue_slug: "pregnant-man-pune", name: "Pune Negroni", slug: "pune-negroni", description: "Gin, sweet vermouth, Campari, smoke.", price_inr: 800, base_spirit: "gin", flavor_tags: ["bitter","smoky","aromatic"], ingredients: [], image_url: null, is_signature: false },
  { id: "cpm5", venue_id: "v26", venue_slug: "pregnant-man-pune", name: "Saturday Sour", slug: "saturday-sour", description: "Whisky, honey, lemon, smoke.", price_inr: 750, base_spirit: "whisky", flavor_tags: ["smoky","sweet","tart"], ingredients: [], image_url: null, is_signature: false },
  { id: "cpm6", venue_id: "v26", venue_slug: "pregnant-man-pune", name: "Cult Margarita", slug: "cult-margarita", description: "Tequila, lime, agave, chili salt.", price_inr: 700, base_spirit: "tequila", flavor_tags: ["citrus","spicy","tart"], ingredients: [], image_url: null, is_signature: false },
  { id: "cpm7", venue_id: "v26", venue_slug: "pregnant-man-pune", name: "Seasonal Spritz", slug: "seasonal-spritz-pm", description: "Whatever's in season. Ask the bar.", price_inr: 750, base_spirit: "varies", flavor_tags: ["seasonal","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "cpm8", venue_id: "v26", venue_slug: "pregnant-man-pune", name: "Cardamom Old Fashioned", slug: "cardamom-of", description: "Bourbon, cardamom syrup, bitters.", price_inr: 800, base_spirit: "bourbon", flavor_tags: ["spiced","boozy","aromatic"], ingredients: [], image_url: null, is_signature: false },

  // TOIT PUNE
  { id: "cti1", venue_id: "v27", venue_slug: "toit-pune", name: "Tropical IPA Sour", slug: "tropical-ipa-sour", description: "House IPA, pineapple, lime, agave.", price_inr: 500, base_spirit: "beer", flavor_tags: ["tropical","tart","crisp"], ingredients: [], image_url: null, is_signature: true },
  { id: "cti2", venue_id: "v27", venue_slug: "toit-pune", name: "Toit Mule", slug: "toit-mule", description: "Vodka, house ginger beer, lime.", price_inr: 600, base_spirit: "vodka", flavor_tags: ["spicy","refreshing","tart"], ingredients: [], image_url: null, is_signature: false },
  { id: "cti3", venue_id: "v27", venue_slug: "toit-pune", name: "Beerita", slug: "beerita", description: "Tequila, lime, beer top.", price_inr: 550, base_spirit: "tequila", flavor_tags: ["citrus","casual","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "cti4", venue_id: "v27", venue_slug: "toit-pune", name: "Hop Sour", slug: "hop-sour", description: "Whisky, hops, lemon, honey.", price_inr: 700, base_spirit: "whisky", flavor_tags: ["herbal","tart","sweet"], ingredients: [], image_url: null, is_signature: false },
  { id: "cti5", venue_id: "v27", venue_slug: "toit-pune", name: "Brewer's Garden", slug: "brewers-garden", description: "Gin, basil, lime, tonic.", price_inr: 600, base_spirit: "gin", flavor_tags: ["herbal","crisp","refreshing"], ingredients: [], image_url: null, is_signature: false },
  { id: "cti6", venue_id: "v27", venue_slug: "toit-pune", name: "Stout Old Fashioned", slug: "stout-of", description: "Bourbon, stout reduction, bitters.", price_inr: 750, base_spirit: "bourbon", flavor_tags: ["rich","bitter","boozy"], ingredients: [], image_url: null, is_signature: false },
  { id: "cti7", venue_id: "v27", venue_slug: "toit-pune", name: "Tap Spritz", slug: "tap-spritz", description: "Beer, Aperol, soda, orange.", price_inr: 550, base_spirit: "beer", flavor_tags: ["bitter","crisp","casual"], ingredients: [], image_url: null, is_signature: false },
  { id: "cti8", venue_id: "v27", venue_slug: "toit-pune", name: "Pilsner Mary", slug: "pilsner-mary", description: "Vodka, tomato, pilsner, spices.", price_inr: 600, base_spirit: "vodka", flavor_tags: ["savory","spicy","casual"], ingredients: [], image_url: null, is_signature: false },
];

const venues: VenueWithCity[] = [
  { id: "v1", city_id: "1", cities: cities[0], name: "The Bombay Canteen", slug: "the-bombay-canteen-mumbai", tagline: "A love letter to Indian regional cuisine", description: "Modern Indian institution pairing forgotten regional dishes with cocktails built from the subcontinent's pantry - kokum, gulkand, gondhoraj lime. The corner of Kamala Mills where the new Indian restaurant movement was born.", address: "Process House, Kamala Mills, Lower Parel", neighborhood: "Lower Parel", lat: 19.0117, lng: 72.8295, price_band: 3, phone: null, instagram: "thebombaycanteen", website: null, hero_image: "https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=1600&q=80", gallery: null, opening_hours: null, vibe_tags: ["modern indian","regional","dinner","date night"], is_featured: true, is_published: true },
  { id: "v2", city_id: "1", cities: cities[0], name: "Soka", slug: "soka-mumbai", tagline: "Japanese precision meets Indian ingredients", description: "A Bandra tasting-menu bar that treats cocktails like omakase - no menu, just a conversation about what you feel like. The room is tiny, the seats are counter-side, the ice is crystal clear.", address: "24th Road, Khar West", neighborhood: "Bandra West", lat: 19.0725, lng: 72.8350, price_band: 4, phone: null, instagram: "soka.mumbai", website: null, hero_image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=1600&q=80", gallery: null, opening_hours: null, vibe_tags: ["omakase","intimate","japanese","reservation only"], is_featured: true, is_published: true },
  { id: "v3", city_id: "1", cities: cities[0], name: "O Pedro", slug: "o-pedro-mumbai", tagline: "Goa in a glass, in the middle of BKC", description: "An ode to Goa - cashew feni cocktails, kokum sours, seafood that smells like the Mandovi at low tide. Tropical without being touristy.", address: "Jet Airways Godrej BKC, Bandra East", neighborhood: "BKC", lat: 19.0625, lng: 72.8680, price_band: 3, phone: null, instagram: "opedromumbai", website: null, hero_image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=1600&q=80", gallery: null, opening_hours: null, vibe_tags: ["goan","tropical","large groups","brunch"], is_featured: true, is_published: true },
  { id: "v4", city_id: "1", cities: cities[0], name: "Slink and Bardot", slug: "slink-bardot-mumbai", tagline: "Parisian cabaret on the Worli seaface", description: "Red velvet banquettes, a burlesque stage, and a bartender who treats a French 75 like a religious text. Go for date night, stay for the 1am jazz set.", address: "Sanatan Pereira Bungalow, Worli Village", neighborhood: "Worli", lat: 19.0050, lng: 72.8150, price_band: 4, phone: null, instagram: "slinkandbardot", website: null, hero_image: "https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=1600&q=80", gallery: null, opening_hours: null, vibe_tags: ["cabaret","live music","date night","late night"], is_featured: false, is_published: true },
  { id: "v5", city_id: "1", cities: cities[0], name: "Americano", slug: "americano-mumbai", tagline: "All-day Italian with aperitivo hour", description: "Start with a Negroni at 5pm, slide into dinner, end with amaro. A proper European bar transplanted to Kamala Mills.", address: "Todi Mills, Lower Parel", neighborhood: "Lower Parel", lat: 19.0122, lng: 72.8298, price_band: 3, phone: null, instagram: "americanomumbai", website: null, hero_image: "https://images.unsplash.com/photo-1551024601-bec78aea704b?w=1600&q=80", gallery: null, opening_hours: null, vibe_tags: ["italian","aperitivo","wine","casual"], is_featured: false, is_published: true },
  { id: "v6", city_id: "1", cities: cities[0], name: "Bastian at The Oberoi", slug: "bastian-oberoi-mumbai", tagline: "Seafood and showmanship at Nariman Point", description: "Upscale seafood with harbor views, a martini trolley, and a wine list that runs thirty pages deep.", address: "The Oberoi, Nariman Point", neighborhood: "Nariman Point", lat: 18.9260, lng: 72.8230, price_band: 4, phone: null, instagram: "bastianhospitality", website: null, hero_image: "https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=1600&q=80", gallery: null, opening_hours: null, vibe_tags: ["seafood","premium","view","celebration"], is_featured: false, is_published: true },
  { id: "v7", city_id: "2", cities: cities[1], name: "Sidecar", slug: "sidecar-delhi", tagline: "World's 50 Best — and you can feel why", description: "India's most globally recognized bar in a GK2 basement. Every drink references a place - Punjab, Chettinad, the Konkan coast - and executes it with clarity most Western bars cannot match.", address: "N-12, N Block Market, Greater Kailash II", neighborhood: "Greater Kailash II", lat: 28.5280, lng: 77.2425, price_band: 4, phone: null, instagram: "sidecardelhi", website: null, hero_image: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=1600&q=80", gallery: null, opening_hours: null, vibe_tags: ["world's 50 best","modern indian","reservation only","hall of fame"], is_featured: true, is_published: true },
  { id: "v8", city_id: "2", cities: cities[1], name: "Home", slug: "home-delhi", tagline: "Varun Sharma's intimate Asia's 50 Best room", description: "Forty seats, no signboard, and a cocktail program built around Indian home pantries - ghee-washed spirits, pickled fruit shrubs, tadka bitters. Asia's 50 Best three years running.", address: "DLF Avenue, Saket", neighborhood: "Saket", lat: 28.5240, lng: 77.2168, price_band: 4, phone: null, instagram: "home.saket", website: null, hero_image: "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=1600&q=80", gallery: null, opening_hours: null, vibe_tags: ["asia's 50 best","intimate","reservation only","modern indian"], is_featured: true, is_published: true },
  { id: "v9", city_id: "2", cities: cities[1], name: "Lair", slug: "lair-delhi", tagline: "Aerocity speakeasy with a secret door", description: "Walk past the hotel lobby, find the unmarked black door, ring the bell. Inside: dim amber lighting, a 12-seat bar, bartenders who don't hand you a menu.", address: "Andaz Delhi, Aerocity", neighborhood: "Aerocity", lat: 28.5540, lng: 77.1240, price_band: 4, phone: null, instagram: "lair.delhi", website: null, hero_image: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=1600&q=80", gallery: null, opening_hours: null, vibe_tags: ["speakeasy","hidden","late night","intimate"], is_featured: false, is_published: true },
  { id: "v10", city_id: "2", cities: cities[1], name: "PCO Pass Code Only", slug: "pco-delhi", tagline: "Delhi's original prohibition-era speakeasy", description: "The one that started it all in 2012. Walk through the fake laundromat, find the velvet curtain. Classic cocktails executed with obsessive precision.", address: "Vasant Vihar", neighborhood: "Vasant Vihar", lat: 28.5580, lng: 77.1580, price_band: 3, phone: null, instagram: "pcodelhi", website: null, hero_image: "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=1600&q=80", gallery: null, opening_hours: null, vibe_tags: ["speakeasy","classic cocktails","hidden","og"], is_featured: true, is_published: true },
  { id: "v11", city_id: "2", cities: cities[1], name: "ZLB 23", slug: "zlb-23-delhi", tagline: "Jazz basement under The Leela", description: "Underground jazz bar doing live music Wed-Sat, serving martinis cold enough to make your forehead hurt. Suits, saxophones, low conversation.", address: "The Leela Palace, Chanakyapuri", neighborhood: "Chanakyapuri", lat: 28.5980, lng: 77.1880, price_band: 4, phone: null, instagram: "zlb23", website: null, hero_image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=1600&q=80", gallery: null, opening_hours: null, vibe_tags: ["jazz","live music","hotel bar","date night"], is_featured: false, is_published: true },
  { id: "v12", city_id: "2", cities: cities[1], name: "Teddy Boy", slug: "teddy-boy-delhi", tagline: "A speakeasy stacked into a bungalow attic", description: "Fifty seats, hand-painted wallpaper, a bartender who will argue with you about mezcal for forty minutes. Meherchand's best-kept secret.", address: "Meherchand Market, Lodi Colony", neighborhood: "Meherchand Market", lat: 28.5870, lng: 77.2250, price_band: 3, phone: null, instagram: "teddyboydelhi", website: null, hero_image: "https://images.unsplash.com/photo-1541976844346-f18aeac57b06?w=1600&q=80", gallery: null, opening_hours: null, vibe_tags: ["speakeasy","mezcal","intimate","late night"], is_featured: false, is_published: true },
  { id: "v13", city_id: "3", cities: cities[2], name: "The Permit Room", slug: "permit-room-bangalore", tagline: "Modern South Indian with regional spirits", description: "A love letter to South Indian drinking culture - arrack, feni, toddy, all treated like the serious spirits they are. The sambar is also excellent.", address: "Church Street", neighborhood: "Church Street", lat: 12.9740, lng: 77.6070, price_band: 3, phone: null, instagram: "thepermitroom", website: null, hero_image: "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=1600&q=80", gallery: null, opening_hours: null, vibe_tags: ["south indian","regional spirits","dinner","casual"], is_featured: true, is_published: true },
  { id: "v14", city_id: "3", cities: cities[2], name: "Cirrus 9", slug: "cirrus-9-bangalore", tagline: "Rooftop cocktails on the 9th floor of The Leela", description: "Sunset views, a 40-page whisky list, and a cocktail menu organized by mood. One of the few true rooftop bars in Bangalore.", address: "The Leela Palace, Kodihalli", neighborhood: "Kodihalli", lat: 12.9595, lng: 77.6485, price_band: 4, phone: null, instagram: "cirrus9", website: null, hero_image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=1600&q=80", gallery: null, opening_hours: null, vibe_tags: ["rooftop","view","hotel bar","whisky"], is_featured: false, is_published: true },
  { id: "v15", city_id: "3", cities: cities[2], name: "Bastian Oberoi Bangalore", slug: "bastian-oberoi-blr", tagline: "Mid-century glam meets Asian seafood", description: "Green velvet, brass details, a raw bar, and a signature Orchid Martini that deserves its own page.", address: "The Oberoi, MG Road", neighborhood: "MG Road", lat: 12.9710, lng: 77.6090, price_band: 4, phone: null, instagram: "bastianhospitality", website: null, hero_image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=1600&q=80", gallery: null, opening_hours: null, vibe_tags: ["seafood","glam","dinner","celebration"], is_featured: false, is_published: true },
  { id: "v16", city_id: "3", cities: cities[2], name: "Toca Rooftop", slug: "toca-rooftop-blr", tagline: "Social drinking with a city skyline", description: "The kind of place you end up on a Friday without planning to. Strong drinks, table service, a crowd that skews 25-35.", address: "JW Marriott, Vittal Mallya Road", neighborhood: "Vittal Mallya Road", lat: 12.9720, lng: 77.5960, price_band: 3, phone: null, instagram: "toca.rooftop", website: null, hero_image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=1600&q=80", gallery: null, opening_hours: null, vibe_tags: ["rooftop","social","friday night","crowd"], is_featured: false, is_published: true },
  { id: "v17", city_id: "3", cities: cities[2], name: "Plan B Loaded", slug: "plan-b-loaded-blr", tagline: "Indiranagar's reliable late-night spot", description: "Not fancy, not trying to be. Just good drinks, solid food, and a crowd that stays past 1am.", address: "12th Main, Indiranagar", neighborhood: "Indiranagar", lat: 12.9784, lng: 77.6408, price_band: 2, phone: null, instagram: "planb.loaded", website: null, hero_image: "https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=1600&q=80", gallery: null, opening_hours: null, vibe_tags: ["neighborhood","late night","casual","affordable"], is_featured: false, is_published: true },
  { id: "v18", city_id: "4", cities: cities[3], name: "Soro", slug: "soro-goa", tagline: "The village winehouse, reimagined", description: "An Assagao farmhouse turned cocktail bar, with a garden that fills up by 9pm and a menu built around feni, kokum, and whatever is growing in the backyard.", address: "Anjuna-Mapusa Road, Assagao", neighborhood: "Assagao", lat: 15.5870, lng: 73.7630, price_band: 3, phone: null, instagram: "soro.goa", website: null, hero_image: "https://images.unsplash.com/photo-1552566626-52f8b828add9?w=1600&q=80", gallery: null, opening_hours: null, vibe_tags: ["garden","goan","feni","date night"], is_featured: true, is_published: true },
  { id: "v19", city_id: "4", cities: cities[3], name: "For the Record Vinyl Bar", slug: "for-the-record-goa", tagline: "A record store where they also make cocktails", description: "Vinyl-only soundtrack, highball focus, zero phones on the bar. The most disciplined drinking experience in Goa.", address: "Anjuna-Mapusa Road, Assagao", neighborhood: "Assagao", lat: 15.5885, lng: 73.7640, price_band: 3, phone: null, instagram: "fortherecord.goa", website: null, hero_image: "https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=1600&q=80", gallery: null, opening_hours: null, vibe_tags: ["listening bar","highball","japanese","vinyl"], is_featured: true, is_published: true },
  { id: "v20", city_id: "4", cities: cities[3], name: "Tesouro", slug: "tesouro-goa", tagline: "Portuguese speakeasy in a Parra house", description: "Walk through the blue door on the main road and find a ten-table room pouring vinho verde cocktails and serving petiscos till 2am.", address: "Parra Main Road, Parra", neighborhood: "Parra", lat: 15.5720, lng: 73.8010, price_band: 3, phone: null, instagram: "tesouro.goa", website: null, hero_image: "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=1600&q=80", gallery: null, opening_hours: null, vibe_tags: ["speakeasy","portuguese","late night","hidden"], is_featured: false, is_published: true },
  { id: "v21", city_id: "4", cities: cities[3], name: "Antares", slug: "antares-goa", tagline: "Beach club with sunset cocktails", description: "A cliffside spot at Vagator. Afternoon pool hangs roll into sunset cocktails roll into DJ sets.", address: "Ozran Beach Road, Vagator", neighborhood: "Vagator", lat: 15.6000, lng: 73.7430, price_band: 4, phone: null, instagram: "antaresgoa", website: null, hero_image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=1600&q=80", gallery: null, opening_hours: null, vibe_tags: ["beach club","sunset","dj","pool"], is_featured: false, is_published: true },
  { id: "v22", city_id: "4", cities: cities[3], name: "Mojigao", slug: "mojigao-goa", tagline: "Garden bar with a mezcal obsession", description: "Fairy lights through the mango trees, a 40-bottle mezcal list, and tacos that could pass in Mexico City.", address: "Assagao-Anjuna Road, Assagao", neighborhood: "Assagao", lat: 15.5890, lng: 73.7655, price_band: 3, phone: null, instagram: "mojigao", website: null, hero_image: "https://images.unsplash.com/photo-1541976844346-f18aeac57b06?w=1600&q=80", gallery: null, opening_hours: null, vibe_tags: ["garden","mezcal","casual","outdoor"], is_featured: false, is_published: true },
  { id: "v23", city_id: "5", cities: cities[4], name: "The Moonshine Project", slug: "moonshine-project-hyd", tagline: "Hyderabad's craft cocktail flag-bearer", description: "A tight 30-seat room in Jubilee Hills doing serious work with a city that mostly drinks whisky on rocks. Ask for the off-menu Old Monk old fashioned.", address: "Road No. 36, Jubilee Hills", neighborhood: "Jubilee Hills", lat: 17.4310, lng: 78.4080, price_band: 3, phone: null, instagram: "themoonshineproject", website: null, hero_image: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=1600&q=80", gallery: null, opening_hours: null, vibe_tags: ["craft cocktails","intimate","local favorite","date night"], is_featured: true, is_published: true },
  { id: "v24", city_id: "5", cities: cities[4], name: "Over the Moon", slug: "over-the-moon-hyd", tagline: "Banjara Hills rooftop with city lights", description: "Panoramic city views, a wood-fired pizza oven, and a cocktail menu that actually reads well.", address: "Road No. 3, Banjara Hills", neighborhood: "Banjara Hills", lat: 17.4150, lng: 78.4480, price_band: 3, phone: null, instagram: "overthemoon.hyd", website: null, hero_image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=1600&q=80", gallery: null, opening_hours: null, vibe_tags: ["rooftop","view","casual","date night"], is_featured: false, is_published: true },
  { id: "v25", city_id: "5", cities: cities[4], name: "Altitude", slug: "altitude-hyd", tagline: "Hotel bar with a panoramic wraparound", description: "The 13th floor of Hotel Minerva, with 270 degree city views and a classic hotel bar program.", address: "Hotel Minerva, Sarojini Devi Road", neighborhood: "Secunderabad", lat: 17.4400, lng: 78.4980, price_band: 3, phone: null, instagram: "altitudehyd", website: null, hero_image: "https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=1600&q=80", gallery: null, opening_hours: null, vibe_tags: ["hotel bar","view","classic","late night"], is_featured: false, is_published: true },
  { id: "v26", city_id: "6", cities: cities[5], name: "The Pregnant Man", slug: "pregnant-man-pune", tagline: "Koregaon Park's cult cocktail spot", description: "One of Pune's most serious craft cocktail rooms. Small menu, rotating seasonal specials, bartenders who remember your last drink.", address: "Lane 7, Koregaon Park", neighborhood: "Koregaon Park", lat: 18.5350, lng: 73.8955, price_band: 3, phone: null, instagram: "thepregnantman.pune", website: null, hero_image: "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=1600&q=80", gallery: null, opening_hours: null, vibe_tags: ["craft cocktails","neighborhood","casual","cult favorite"], is_featured: true, is_published: true },
  { id: "v27", city_id: "6", cities: cities[5], name: "Toit Pune", slug: "toit-pune", tagline: "Craft microbrewery with cocktail chops", description: "The Bangalore original's Pune cousin. Known for beer but the cocktail menu punches well above its weight.", address: "Lane 7, North Main Road, Koregaon Park", neighborhood: "Koregaon Park", lat: 18.5340, lng: 73.8960, price_band: 3, phone: null, instagram: "toit.pune", website: null, hero_image: "https://images.unsplash.com/photo-1551024601-bec78aea704b?w=1600&q=80", gallery: null, opening_hours: null, vibe_tags: ["microbrewery","large groups","casual","food"], is_featured: false, is_published: true },
];

export async function getAllVenues(): Promise<VenueWithCity[]> {
  return venues.sort((a, b) => (b.is_featured ? 1 : 0) - (a.is_featured ? 1 : 0));
}

export async function getFeaturedVenues(limit = 6): Promise<VenueWithCity[]> {
  return venues.filter(v => v.is_featured).slice(0, limit);
}

export async function getVenueBySlug(slug: string): Promise<VenueWithCocktails | null> {
  const venue = venues.find(v => v.slug === slug);
  if (!venue) return null;
  const venueCocktails = cocktails.filter(c => c.venue_slug === slug);
  return { ...venue, cocktails: venueCocktails };
}

export async function getAllCities(): Promise<City[]> {
  return [...cities].sort((a, b) => a.name.localeCompare(b.name));
}

export async function getCityBySlug(slug: string): Promise<City | null> {
  return cities.find(c => c.slug === slug) ?? null;
}

export async function getVenuesByCity(citySlug: string): Promise<VenueWithCity[]> {
  return venues
    .filter(v => v.cities?.slug === citySlug)
    .sort((a, b) => (b.is_featured ? 1 : 0) - (a.is_featured ? 1 : 0));
}

export async function getSignatureCocktails(limit = 9) {
  return cocktails.filter(c => c.is_signature).slice(0, limit);
}
